import 'package:flutter/material.dart';

/// Simplified localization map with key translations for each language.
class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const supportedLocales = [
    Locale('en'), Locale('ml'), Locale('ta'), Locale('kn'), Locale('te'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'AlmaDiet',
      'welcome': 'Welcome to AlmaDiet',
      'subtitle': 'Your personalized pregnancy diet companion',
      'login': 'Login',
      'sign_in': 'Sign In',
      'register': 'Register',
      'create_account': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'name': 'Full Name',
      'phone': 'Phone Number',
      'home': 'Home',
      'diet_plan': 'Diet Plan',
      'diet': 'Diet',
      'emergency': 'Emergency',
      'profile': 'Profile',
      'health_input': 'Health Data',
      'generate_plan': 'Generate Diet Plan',
      'trimester': 'Trimester',
      'week': 'Week',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'snacks': 'Snacks',
      'calories': 'Calories',
      'protein': 'Protein',
      'iron': 'Iron',
      'calcium': 'Calcium',
      'settings': 'Settings',
      'language': 'Language',
      'logout': 'Logout',
      'report': 'Report',
      'report_emergency': 'Report Emergency',
      'weight': 'Weight (kg)',
      'hemoglobin': 'Hemoglobin (g/dL)',
      'blood_sugar': 'Blood Sugar (mg/dL)',
      'blood_pressure': 'Blood Pressure',
      'submit': 'Submit',
      'get_started': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'welcome_back': 'Welcome Back',
      'sign_in_continue': 'Sign in to continue your journey 🌸',
      'no_account': "Don't have an account? ",
      'has_account': 'Already have an account? ',
      'start_journey': 'Start your healthy pregnancy journey 🌸',
      'hello': 'Hello',
      'companion': 'Your pregnancy diet companion',
      'daily_tip': 'Daily Tip',
      'health_input_label': 'Health\nInput',
      'my_diet_plan': 'My Diet\nPlan',
      'emergency_help': 'Emergency\nHelp',
      'latest_health': 'Latest Health Data',
      'todays_meals': "Today's Meals",
      'no_plan_yet': 'No Diet Plan Yet',
      'no_plan_desc': 'Submit your health data to get a personalized meal plan',
      'start_now': 'Start Now',
      'loading_dashboard': 'Loading your dashboard...',
      'loading_meal_plan': 'Loading your meal plan...',
      'no_diet_plan': 'No Diet Plan',
      'no_diet_desc': 'Submit your health data first\nto generate a personalized meal plan',
      'add_health_data': 'Add Health Data',
      'daily_targets': 'Daily Targets',
      'dietary_alerts': 'Dietary Alerts',
      'all_clear': 'All Clear',
      'no_emergencies': 'No emergencies reported.\nTap below if you need help.',
      'active': 'ACTIVE',
      'resolved': 'RESOLVED',
      'mark_resolved': 'Mark as Resolved',
      'select_type_desc': 'Select the type and describe your situation',
      'describe_situation': 'Describe the situation...',
      'submit_report': 'Submit Report',
      'pregnancy_info': 'Pregnancy Info',
      'health_vitals': 'Health Vitals',
      'dietary_pref': 'Dietary Preference',
      'bp_systolic': 'BP Systolic',
      'bp_diastolic': 'BP Diastolic',
      'fasting_sugar': 'Fasting Blood Sugar',
      'auto_generate': 'Auto-generate diet plan',
      'generate_after': 'Generate meals after submitting',
      'submit_generate': 'Submit & Generate',
      'health_tip': 'Enter your monthly health data for personalized diet recommendations.',
      'health_submitted': '✅ Health data submitted! Meal plan ready.',
      'health_failed': '❌ Failed to submit',
      'region': 'Region',
      'age': 'Age',
      'height': 'Height',
      'pre_weight': 'Pre-pregnancy Weight',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile updated! ✅',
      'profile_photo': 'Profile Photo',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'remove': 'Remove',
      'exit_title': 'Exit AlmaDiet?',
      'exit_msg': 'Take care of yourself and your baby! 🌸\nAre you sure you want to exit?',
      'stay': 'Stay',
      'exit': 'Exit',
      'page_not_found': 'Page Not Found',
      'go_home': 'Go Home',
      'non_veg': 'Non-Veg',
      'veg': 'Veg',
      'eggetarian': 'Eggetarian',
      'first': 'First',
      'second': 'Second',
      'third': 'Third',
      'onboard_1_title': 'Eat Smart for Two',
      'onboard_1_desc': 'Personalized South Indian meals crafted for every trimester of your pregnancy journey.',
      'onboard_2_title': 'AI-Powered Nutrition',
      'onboard_2_desc': 'Our ML model analyzes your health data to recommend the perfect meals for you and your baby.',
      'onboard_3_title': 'Regional & Multilingual',
      'onboard_3_desc': 'Kerala, Tamil Nadu, Karnataka, Andhra — meals in your language and from your region.',
      'analyzing': 'Analyzing your health data\nand generating your meal plan... 🍽️',
      'loading': 'Loading...',
      'gestational_diabetes': 'Gestational Diabetes',
      'preeclampsia': 'Preeclampsia',
      'anemia': 'Anemia',
      'bleeding': 'Bleeding',
      'severe_nausea': 'Severe Nausea',
    },
    'ml': {
      'app_name': 'അൽമഡയറ്റ്',
      'welcome': 'അൽമഡയറ്റിലേക്ക് സ്വാഗതം',
      'subtitle': 'നിങ്ങളുടെ ഗർഭകാല ഭക്ഷണ സഹായി',
      'login': 'ലോഗിൻ',
      'sign_in': 'സൈൻ ഇൻ',
      'register': 'രജിസ്റ്റർ',
      'create_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'email': 'ഇമെയിൽ',
      'password': 'പാസ്‌വേഡ്',
      'name': 'പൂർണ്ണ നാമം',
      'phone': 'ഫോൺ നമ്പർ',
      'home': 'ഹോം',
      'diet_plan': 'ഭക്ഷണ പ്ലാൻ',
      'diet': 'ഭക്ഷണം',
      'emergency': 'അടിയന്തരം',
      'profile': 'പ്രൊഫൈൽ',
      'health_input': 'ആരോഗ്യ ഡാറ്റ',
      'trimester': 'ത്രൈമാസം',
      'week': 'ആഴ്ച',
      'breakfast': 'പ്രഭാതഭക്ഷണം',
      'lunch': 'ഉച്ചഭക്ഷണം',
      'dinner': 'അത്താഴം',
      'snacks': 'ലഘുഭക്ഷണം',
      'calories': 'കലോറി',
      'protein': 'പ്രോട്ടീൻ',
      'iron': 'ഇരുമ്പ്',
      'calcium': 'കാൽസ്യം',
      'language': 'ഭാഷ',
      'logout': 'ലോഗൗട്ട്',
      'report': 'റിപ്പോർട്ട്',
      'report_emergency': 'അടിയന്തരം റിപ്പോർട്ട്',
      'submit': 'സമർപ്പിക്കുക',
      'get_started': 'ആരംഭിക്കൂ',
      'next': 'അടുത്തത്',
      'skip': 'ഒഴിവാക്കുക',
      'welcome_back': 'സ്വാഗതം',
      'sign_in_continue': 'നിങ്ങളുടെ യാത്ര തുടരാൻ സൈൻ ഇൻ ചെയ്യൂ 🌸',
      'no_account': 'അക്കൗണ്ട് ഇല്ലേ? ',
      'has_account': 'ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ? ',
      'start_journey': 'നിങ്ങളുടെ ആരോഗ്യകരമായ ഗർഭ യാത്ര ആരംഭിക്കൂ 🌸',
      'hello': 'ഹലോ',
      'companion': 'നിങ്ങളുടെ ഗർഭകാല ഭക്ഷണ സഹായി',
      'daily_tip': 'ദൈനംദിന ടിപ്പ്',
      'health_input_label': 'ആരോഗ്യ\nഇൻപുട്ട്',
      'my_diet_plan': 'എന്റെ ഭക്ഷണ\nപ്ലാൻ',
      'emergency_help': 'അടിയന്തര\nസഹായം',
      'latest_health': 'ഏറ്റവും പുതിയ ആരോഗ്യ ഡാറ്റ',
      'todays_meals': 'ഇന്നത്തെ ഭക്ഷണം',
      'no_plan_yet': 'ഭക്ഷണ പ്ലാൻ ഇല്ല',
      'no_plan_desc': 'വ്യക്തിഗത ഭക്ഷണ പ്ലാൻ ലഭിക്കാൻ നിങ്ങളുടെ ആരോഗ്യ ഡാറ്റ സമർപ്പിക്കുക',
      'start_now': 'ഇപ്പോൾ ആരംഭിക്കൂ',
      'loading_dashboard': 'ഡാഷ്ബോർഡ് ലോഡ് ചെയ്യുന്നു...',
      'loading_meal_plan': 'ഭക്ഷണ പ്ലാൻ ലോഡ് ചെയ്യുന്നു...',
      'no_diet_plan': 'ഭക്ഷണ പ്ലാൻ ഇല്ല',
      'no_diet_desc': 'വ്യക്തിഗത ഭക്ഷണ പ്ലാൻ സൃഷ്ടിക്കാൻ\nനിങ്ങളുടെ ആരോഗ്യ ഡാറ്റ സമർപ്പിക്കുക',
      'add_health_data': 'ആരോഗ്യ ഡാറ്റ ചേർക്കുക',
      'daily_targets': 'ദൈനംദിന ലക്ഷ്യങ്ങൾ',
      'dietary_alerts': 'ഭക്ഷണ മുന്നറിയിപ്പുകൾ',
      'all_clear': 'എല്ലാം ക്ലിയർ',
      'no_emergencies': 'അടിയന്തര സാഹചര്യങ്ങൾ റിപ്പോർട്ട് ചെയ്തിട്ടില്ല.\nസഹായം ആവശ്യമെങ്കിൽ താഴെ ടാപ്പ് ചെയ്യുക.',
      'active': 'സജീവം',
      'resolved': 'പരിഹരിച്ചു',
      'mark_resolved': 'പരിഹരിച്ചതായി അടയാളപ്പെടുത്തുക',
      'select_type_desc': 'തരം തിരഞ്ഞെടുത്ത് നിങ്ങളുടെ സാഹചര്യം വിവരിക്കുക',
      'describe_situation': 'സാഹചര്യം വിവരിക്കുക...',
      'submit_report': 'റിപ്പോർട്ട് സമർപ്പിക്കുക',
      'pregnancy_info': 'ഗർഭ വിവരങ്ങൾ',
      'health_vitals': 'ആരോഗ്യ സൂചകങ്ങൾ',
      'dietary_pref': 'ഭക്ഷണ മുൻഗണന',
      'auto_generate': 'ഭക്ഷണ പ്ലാൻ സ്വയം സൃഷ്ടിക്കുക',
      'generate_after': 'സമർപ്പിച്ചതിനുശേഷം ഭക്ഷണം സൃഷ്ടിക്കുക',
      'submit_generate': 'സമർപ്പിക്കുക & സൃഷ്ടിക്കുക',
      'health_tip': 'വ്യക്തിഗത ഭക്ഷണ ശുപാർശകൾക്കായി നിങ്ങളുടെ പ്രതിമാസ ആരോഗ്യ ഡാറ്റ നൽകുക.',
      'region': 'പ്രദേശം',
      'age': 'പ്രായം',
      'edit_profile': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      'save_changes': 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
      'profile_updated': 'പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്തു! ✅',
      'profile_photo': 'പ്രൊഫൈൽ ഫോട്ടോ',
      'camera': 'ക്യാമറ',
      'gallery': 'ഗാലറി',
      'remove': 'നീക്കം',
      'exit_title': 'അൽമഡയറ്റ് ഉപേക്ഷിക്കണോ?',
      'exit_msg': 'നിങ്ങളെയും നിങ്ങളുടെ കുഞ്ഞിനെയും ശ്രദ്ധിക്കൂ! 🌸\nനിങ്ങൾക്ക് ഉറപ്പാണോ?',
      'stay': 'തുടരുക',
      'exit': 'പുറത്തുപോകുക',
      'onboard_1_title': 'രണ്ടുപേർക്ക് വേണ്ടി സ്മാർട്ടായി കഴിക്കൂ',
      'onboard_1_desc': 'നിങ്ങളുടെ ഗർഭ യാത്രയുടെ ഓരോ ത്രൈമാസത്തിനും അനുസൃതമായ ദക്ഷിണ ഇന്ത്യൻ ഭക്ഷണം.',
      'onboard_2_title': 'AI-അധിഷ്ഠിത പോഷണം',
      'onboard_2_desc': 'ഞങ്ങളുടെ ML മോഡൽ നിങ്ങളുടെ ആരോഗ്യ ഡാറ്റ വിശകലനം ചെയ്ത് ഏറ്റവും നല്ല ഭക്ഷണം ശുപാർശ ചെയ്യുന്നു.',
      'onboard_3_title': 'പ്രാദേശിക & ബഹുഭാഷ',
      'onboard_3_desc': 'കേരളം, തമിഴ്‌നാട്, കർണാടക, ആന്ധ്ര — നിങ്ങളുടെ ഭാഷയിലും പ്രദേശത്തുനിന്നുമുള്ള ഭക്ഷണം.',
      'analyzing': 'നിങ്ങളുടെ ആരോഗ്യ ഡാറ്റ വിശകലനം ചെയ്യുന്നു\nഭക്ഷണ പ്ലാൻ സൃഷ്ടിക്കുന്നു... 🍽️',
      'loading': 'ലോഡ് ചെയ്യുന്നു...',
    },
    'ta': {
      'app_name': 'அல்மாடயட்',
      'welcome': 'அல்மாடயட்டுக்கு வரவேற்கிறோம்',
      'subtitle': 'உங்கள் கர்ப்பகால உணவு துணை',
      'login': 'உள்நுழைவு',
      'sign_in': 'உள்நுழை',
      'register': 'பதிவு',
      'create_account': 'கணக்கை உருவாக்கு',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'name': 'முழு பெயர்',
      'phone': 'தொலைபேசி எண்',
      'home': 'முகப்பு',
      'diet_plan': 'உணவு திட்டம்',
      'diet': 'உணவு',
      'emergency': 'அவசரம்',
      'profile': 'சுயவிவரம்',
      'health_input': 'சுகாதார தரவு',
      'trimester': 'மூன்று மாத காலம்',
      'week': 'வாரம்',
      'breakfast': 'காலை உணவு',
      'lunch': 'மதிய உணவு',
      'dinner': 'இரவு உணவு',
      'snacks': 'சிற்றுண்டி',
      'calories': 'கலோரிகள்',
      'protein': 'புரதம்',
      'iron': 'இரும்பு',
      'calcium': 'கால்சியம்',
      'language': 'மொழி',
      'logout': 'வெளியேறு',
      'report': 'அறிக்கை',
      'report_emergency': 'அவசர அறிக்கை',
      'submit': 'சமர்ப்பி',
      'get_started': 'தொடங்குங்கள்',
      'next': 'அடுத்து',
      'skip': 'தவிர்',
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'sign_in_continue': 'உங்கள் பயணத்தைத் தொடர உள்நுழையுங்கள் 🌸',
      'no_account': 'கணக்கு இல்லையா? ',
      'has_account': 'ஏற்கனவே கணக்கு உள்ளதா? ',
      'start_journey': 'உங்கள் ஆரோக்கியமான கர்ப்ப பயணத்தைத் தொடங்குங்கள் 🌸',
      'hello': 'வணக்கம்',
      'companion': 'உங்கள் கர்ப்பகால உணவு துணை',
      'daily_tip': 'தினசரி குறிப்பு',
      'health_input_label': 'சுகாதார\nஉள்ளீடு',
      'my_diet_plan': 'என் உணவு\nதிட்டம்',
      'emergency_help': 'அவசர\nஉதவி',
      'latest_health': 'சமீபத்திய சுகாதார தரவு',
      'todays_meals': 'இன்றைய உணவுகள்',
      'no_plan_yet': 'உணவு திட்டம் இல்லை',
      'no_plan_desc': 'தனிப்பயன் உணவு திட்டத்தைப் பெற உங்கள் சுகாதார தரவை சமர்ப்பிக்கவும்',
      'start_now': 'இப்போது தொடங்குங்கள்',
      'loading_dashboard': 'டாஷ்போர்டை ஏற்றுகிறது...',
      'loading_meal_plan': 'உணவு திட்டத்தை ஏற்றுகிறது...',
      'no_diet_plan': 'உணவு திட்டம் இல்லை',
      'no_diet_desc': 'தனிப்பயன் உணவு திட்டத்தை உருவாக்க\nமுதலில் உங்கள் சுகாதார தரவை சமர்ப்பிக்கவும்',
      'add_health_data': 'சுகாதார தரவைச் சேர்க்கவும்',
      'daily_targets': 'தினசரி இலக்குகள்',
      'dietary_alerts': 'உணவு எச்சரிக்கைகள்',
      'all_clear': 'அனைத்தும் சரி',
      'no_emergencies': 'அவசரநிலைகள் எதுவும் பதிவாகவில்லை.\nஉதவி தேவையென்றால் கீழே தட்டவும்.',
      'active': 'செயலில்',
      'resolved': 'தீர்க்கப்பட்டது',
      'mark_resolved': 'தீர்க்கப்பட்டதாகக் குறிக்கவும்',
      'submit_report': 'அறிக்கையை சமர்ப்பிக்கவும்',
      'pregnancy_info': 'கர்ப்ப தகவல்',
      'health_vitals': 'சுகாதார அளவீடுகள்',
      'dietary_pref': 'உணவு விருப்பம்',
      'auto_generate': 'உணவு திட்டத்தை தானாக உருவாக்கு',
      'generate_after': 'சமர்ப்பித்த பின் உணவுகளை உருவாக்கு',
      'submit_generate': 'சமர்ப்பி & உருவாக்கு',
      'region': 'பகுதி',
      'age': 'வயது',
      'edit_profile': 'சுயவிவரத்தை திருத்து',
      'save_changes': 'மாற்றங்களை சேமி',
      'profile_updated': 'சுயவிவரம் புதுப்பிக்கப்பட்டது! ✅',
      'exit_title': 'அல்மாடயட்டை விட்டு வெளியேறவா?',
      'stay': 'தங்கு',
      'exit': 'வெளியேறு',
      'onboard_1_title': 'இருவருக்கும் புத்திசாலியாக சாப்பிடுங்கள்',
      'onboard_1_desc': 'உங்கள் கர்ப்ப பயணத்தின் ஒவ்வொரு மூன்று மாத காலத்திற்கும் தனிப்பயனாக்கப்பட்ட தென்னிந்திய உணவுகள்.',
      'onboard_2_title': 'AI-இயக்கப்படும் ஊட்டச்சத்து',
      'onboard_2_desc': 'எங்கள் ML மாடல் உங்கள் சுகாதார தரவை பகுப்பாய்வு செய்து சிறந்த உணவுகளை பரிந்துரைக்கிறது.',
      'onboard_3_title': 'பிராந்திய & பன்மொழி',
      'onboard_3_desc': 'கேரளா, தமிழ்நாடு, கர்நாடகா, ஆந்திரா — உங்கள் மொழியிலும் பகுதியிலிருந்தும் உணவுகள்.',
      'analyzing': 'உங்கள் சுகாதார தரவை பகுப்பாய்வு செய்கிறது\nஉணவு திட்டத்தை உருவாக்குகிறது... 🍽️',
      'loading': 'ஏற்றுகிறது...',
    },
    'kn': {
      'app_name': 'ಅಲ್ಮಾಡಯಟ್',
      'welcome': 'ಅಲ್ಮಾಡಯಟ್‌ಗೆ ಸ್ವಾಗತ',
      'subtitle': 'ನಿಮ್ಮ ಗರ್ಭಾವಸ್ಥೆಯ ಆಹಾರ ಸಹಚರ',
      'login': 'ಲಾಗಿನ್',
      'sign_in': 'ಸೈನ್ ಇನ್',
      'register': 'ನೋಂದಣಿ',
      'create_account': 'ಖಾತೆ ರಚಿಸಿ',
      'email': 'ಇಮೇಲ್',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'name': 'ಪೂರ್ಣ ಹೆಸರು',
      'home': 'ಮುಖಪುಟ',
      'diet_plan': 'ಆಹಾರ ಯೋಜನೆ',
      'diet': 'ಆಹಾರ',
      'emergency': 'ತುರ್ತು',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'health_input': 'ಆರೋಗ್ಯ ಡೇಟಾ',
      'breakfast': 'ಉಪಹಾರ',
      'lunch': 'ಊಟ',
      'dinner': 'ರಾತ್ರಿ ಊಟ',
      'snacks': 'ತಿಂಡಿ',
      'language': 'ಭಾಷೆ',
      'logout': 'ಲಾಗ್‌ಔಟ್',
      'submit': 'ಸಲ್ಲಿಸು',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'next': 'ಮುಂದೆ',
      'skip': 'ಬಿಟ್ಟುಬಿಡಿ',
      'welcome_back': 'ಮತ್ತೆ ಸ್ವಾಗತ',
      'hello': 'ನಮಸ್ಕಾರ',
      'companion': 'ನಿಮ್ಮ ಗರ್ಭಾವಸ್ಥೆಯ ಆಹಾರ ಸಹಚರ',
      'daily_tip': 'ದೈನಿಕ ಸಲಹೆ',
      'latest_health': 'ಇತ್ತೀಚಿನ ಆರೋಗ್ಯ ಡೇಟಾ',
      'todays_meals': 'ಇಂದಿನ ಊಟ',
      'no_plan_yet': 'ಆಹಾರ ಯೋಜನೆ ಇಲ್ಲ',
      'start_now': 'ಈಗ ಪ್ರಾರಂಭಿಸಿ',
      'stay': 'ಉಳಿಯಿರಿ',
      'exit': 'ನಿರ್ಗಮಿಸಿ',
      'region': 'ಪ್ರದೇಶ',
      'age': 'ವಯಸ್ಸು',
      'save_changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
      'onboard_1_title': 'ಇಬ್ಬರಿಗಾಗಿ ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ತಿನ್ನಿ',
      'onboard_2_title': 'AI-ಚಾಲಿತ ಪೋಷಣೆ',
      'onboard_3_title': 'ಪ್ರಾದೇಶಿಕ & ಬಹುಭಾಷಾ',
    },
    'te': {
      'app_name': 'అల్మాడైట్',
      'welcome': 'అల్మాడైట్‌కి స్వాగతం',
      'subtitle': 'మీ గర్భధారణ ఆహార సహచరుడు',
      'login': 'లాగిన్',
      'sign_in': 'సైన్ ఇన్',
      'register': 'నమోదు',
      'create_account': 'ఖాతా సృష్టించు',
      'email': 'ఇమెయిల్',
      'password': 'పాస్‌వర్డ్',
      'name': 'పూర్తి పేరు',
      'home': 'హోమ్',
      'diet_plan': 'ఆహార ప్రణాళిక',
      'diet': 'ఆహారం',
      'emergency': 'అత్యవసరం',
      'profile': 'ప్రొఫైల్',
      'health_input': 'ఆరోగ్య డేటా',
      'breakfast': 'అల్పాహారం',
      'lunch': 'భోజనం',
      'dinner': 'రాత్రి భోజనం',
      'snacks': 'చిరుతిండి',
      'language': 'భాష',
      'logout': 'లాగ్‌అవుట్',
      'submit': 'సమర్పించు',
      'get_started': 'ప్రారంభించండి',
      'next': 'తరువాత',
      'skip': 'దాటవేయి',
      'welcome_back': 'మళ్ళీ స్వాగతం',
      'hello': 'నమస్కారం',
      'companion': 'మీ గర్భధారణ ఆహార సహచరుడు',
      'daily_tip': 'రోజువారీ సూచన',
      'latest_health': 'ఇటీవలి ఆరోగ్య డేటా',
      'todays_meals': 'నేటి భోజనాలు',
      'no_plan_yet': 'ఆహార ప్రణాళిక లేదు',
      'start_now': 'ఇప్పుడే ప్రారంభించు',
      'stay': 'ఉండు',
      'exit': 'నిష్క్రమించు',
      'region': 'ప్రాంతం',
      'age': 'వయస్సు',
      'save_changes': 'మార్పులు సేవ్ చేయి',
      'onboard_1_title': 'ఇద్దరికోసం తెలివిగా తినండి',
      'onboard_2_title': 'AI-ఆధారిత పోషణ',
      'onboard_3_title': 'ప్రాంతీయ & బహుభాష',
    },
  };

  String tr(String key) {
    return _localizedValues[locale.languageCode]?[key]
        ?? _localizedValues['en']![key]
        ?? key;
  }

  /// Returns the localized meal name based on the current locale.
  /// Falls back to English name if the localized name is null or empty.
  String mealName(Map<String, dynamic> meal) {
    final lang = locale.languageCode;
    String? localized;
    switch (lang) {
      case 'ta':
        localized = meal['name_tamil'] as String?;
        break;
      case 'ml':
        localized = meal['name_malayalam'] as String?;
        break;
      case 'kn':
        localized = meal['name_kannada'] as String?;
        break;
      case 'te':
        localized = meal['name_telugu'] as String?;
        break;
    }
    if (localized != null && localized.isNotEmpty) return localized;
    return meal['name'] ?? 'Meal';
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ml', 'ta', 'kn', 'te'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
