import 'package:flutter/material.dart';

/// AlmaDiet localization — 5 languages, complete key coverage.
///
/// Invariant (enforced by test/localization_completeness_test.dart):
/// every language defines EXACTLY the same key set as English.
class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const supportedLocales = [
    Locale('en'), Locale('ml'), Locale('ta'), Locale('kn'), Locale('te'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'AlmaDiet',
      'welcome': 'Welcome to AlmaDiet',
      'subtitle': 'Pregnancy nutrition support, in your language',
      'login': 'Login',
      'sign_in': 'Sign In',
      'register': 'Register',
      'create_account': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'name': 'Full Name',
      'phone': 'Phone Number',
      'home': 'Home',
      'diet_plan': 'Diet Plan',
      'diet': 'Meals',
      'urgent_help': 'Urgent Help',
      'emergency_help': 'Urgent\nHelp',
      'profile': 'Profile',
      'health_input': 'Health Data',
      'generate_plan': 'Generate Meal Ideas',
      'trimester': 'Trimester',
      'week': 'Week',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'snacks': 'Snacks',
      'calories': 'Calories',
      'protein': 'Protein',
      'iron': 'Iron',
      'calcium': 'Calcium',
      'settings': 'Settings',
      'language': 'Language',
      'logout': 'Logout',
      'weight': 'Weight (kg)',
      'hemoglobin': 'Hemoglobin (g/dL)',
      'blood_sugar': 'Blood Sugar (mg/dL)',
      'blood_pressure': 'Blood Pressure',
      'submit': 'Submit',
      'get_started': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'welcome_back': 'Welcome Back',
      'sign_in_continue': 'Sign in to continue',
      'no_account': "Don't have an account? ",
      'has_account': 'Already have an account? ',
      'start_journey': 'Organize your pregnancy nutrition',
      'hello': 'Hello',
      'companion': 'Your pregnancy nutrition companion',
      'daily_tip': 'Daily Tip',
      'health_input_label': 'Health\nInput',
      'my_diet_plan': 'My Meal\nIdeas',
      'latest_health': 'Latest Health Data',
      'todays_meals': 'Meal Ideas for Today',
      'no_plan_yet': 'No Meal Ideas Yet',
      'no_plan_desc': 'Submit your health data to get meal ideas based on your preferences',
      'start_now': 'Start Now',
      'loading_dashboard': 'Loading your dashboard...',
      'loading_meal_plan': 'Loading your meal ideas...',
      'no_diet_plan': 'No Meal Plan Yet',
      'no_diet_desc': 'Submit your health data first to get meal ideas for your week',
      'add_health_data': 'Add Health Data',
      'daily_targets': 'Reference Values',
      'dietary_alerts': 'Safety Notes',
      'pregnancy_info': 'Pregnancy Info',
      'health_vitals': 'Health Vitals',
      'dietary_pref': 'Dietary Preference',
      'bp_systolic': 'BP Systolic',
      'bp_diastolic': 'BP Diastolic',
      'fasting_sugar': 'Fasting Blood Sugar',
      'auto_generate': 'Create meal ideas after saving',
      'generate_after': 'Get a week of meal ideas once your data is saved',
      'submit_generate': 'Save & Get Ideas',
      'health_tip': 'Your information helps organize safe meal ideas. It is not used to diagnose anything.',
      'health_submitted': 'Health data saved! Meal ideas are ready.',
      'health_failed': 'Could not save your data',
      'fix_errors_first': 'Please correct the highlighted fields first.',
      'profile_completion_title': 'Complete Your Profile',
      'profile_completion_hint': 'AlmaDiet calculates your pre-pregnancy BMI and pregnancy week on the server — you never enter BMI yourself.',
      'server_calculated_note': 'Calculated for you on the server (for your information only)',
      'pre_pregnancy_bmi': 'Pre-pregnancy BMI',
      'pregnancy_week': 'Week',
      'height_cm_label': 'Height (cm)',
      'height_cm_hint': 'e.g. 160',
      'prepreg_weight_label': 'Pre-pregnancy weight (kg)',
      'prepreg_weight_hint': 'Your weight before pregnancy',
      'lmp_date_label': 'First day of last period (LMP)',
      'lmp_date_hint': 'Tap to pick a date — or ask your clinician for your due date',
      'allergies_label': 'Allergies — meals containing these are always excluded',
      'cooking_time_label': 'Cooking time preference',
      'budget_label': 'Budget preference',
      'dislikes_label': 'Ingredients you dislike',
      'dislikes_hint': 'e.g. mushroom, bitter gourd',
      'save_and_continue': 'Save & Continue',
      'profile_saved_incomplete': 'Saved — but a few required details are still missing.',
      'err_enter_height_weight': 'Please enter your height and pre-pregnancy weight.',
      'profile_incomplete_title': 'A Few Details Needed',
      'profile_incomplete_msg': 'Personalized meal suggestions need your height, pre-pregnancy weight, and pregnancy date. AlmaDiet calculates everything else on the server.',
      'complete_profile': 'Complete Profile',
      'clinician_review_title': 'Clinician Guidance Recommended',
      'clinician_review_msg': 'Your health context needs personal clinician input before customized meal suggestions. Please talk to your doctor, midwife, or a registered dietitian.',
      'no_safe_suggestion_title': 'No Safe Suggestions Right Now',
      'no_safe_suggestion_msg': 'No meals in the reviewed catalog match your safety profile. For personalized guidance, please talk to your doctor, midwife, or a registered dietitian.',
      'consent_required_diet_msg': 'Please review and accept the consent screen before personalized suggestions.',
      'review_consent': 'Review Consent',
      'suggested_based_on': 'Suggested based on your saved preferences and reviewed meal content.',
      'filtered_using': 'Filtered using your saved allergy and dietary settings.',
      'err_must_be_number': 'must be a number',
      'err_must_be_between': 'must be between {min} and {max}',
      'vital_hint_weight': 'Typical range: 30–200 kg',
      'vital_hint_hemoglobin': 'Typical range: 3–20 g/dL',
      'vital_hint_bp_sys': 'Typical range: 60–250 mmHg',
      'vital_hint_bp_dia': 'Typical range: 40–150 mmHg',
      'vital_hint_sugar': 'Typical range: 20–600 mg/dL',
      'region': 'Region',
      'age': 'Age',
      'height': 'Height',
      'pre_weight': 'Pre-pregnancy Weight',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile updated!',
      'profile_photo': 'Profile Photo',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'remove': 'Remove',
      'exit_title': 'Exit AlmaDiet?',
      'exit_msg': 'Take care of yourself!\nAre you sure you want to exit?',
      'stay': 'Stay',
      'exit': 'Exit',
      'page_not_found': 'Page Not Found',
      'go_home': 'Go Home',
      'non_veg': 'Non-Veg',
      'veg': 'Veg',
      'eggetarian': 'Eggetarian',
      'first': 'First',
      'second': 'Second',
      'third': 'Third',
      'onboard_1_title': 'Eat Well for Two',
      'onboard_1_desc': 'Organize South Indian meal ideas for every trimester of your pregnancy.',
      'onboard_2_title': 'Clear, Safe Suggestions',
      'onboard_2_desc': 'Meal ideas respect your allergies, preferences, and trimester — with the reasons shown for each suggestion.',
      'onboard_3_title': 'Regional & Multilingual',
      'onboard_3_desc': 'Kerala, Tamil Nadu, Karnataka, Andhra — meals in your language and from your region.',
      'analyzing': 'Saving your health data\nand preparing meal ideas...',
      'loading': 'Loading...',
      'error_generic': 'Something went wrong. Please try again.',
      'retry': 'Retry',
      'urgent_note_title': 'Note for your clinician',
      'urgent_note_hint': 'Describe what you are feeling, when it started, and how often...',
      'save_note': 'Save Note',
      'note_saved': 'Note saved. Share it with your clinician.',
      'add_note': 'Add Note',
      'urgent_app_cannot': 'This app cannot assess emergencies',
      'urgent_disclaimer_fallback': 'AlmaDiet cannot assess emergencies or urgent symptoms. This screen provides safety information only and is not medical advice.',
      'urgent_warning_signs': 'Warning signs — seek medical care',
      'urgent_contacts': 'Who to contact',
      'emergency_number': 'Emergency',
      'ambulance_number': 'Ambulance',
      'urgent_clinician_checklist': 'Before you call your clinician',
      'your_notes': 'Your notes',
      'vitals_optional': 'All fields optional — leave blank anything you do not know. Nothing is guessed.',
      'allergies': 'Allergies',
      'allergies_hint': 'Foods listed here are hard-excluded from every meal suggestion.',
      'allergy_placeholder': 'e.g. peanut, egg, shrimp...',
      'add_allergy': 'Add allergy',
      'swap_meal': 'Swap meal',
      'swap_done': 'Meal swapped — safety filters re-applied.',
      'why_suggested': 'Suggested because',
      'reference_only': 'Reference values only — not a prescription. Discuss targets with your clinician.',
      'day': 'Day',
      'today_badge': 'Today',
      'allergens_section': 'Allergens',
      'no_known_allergens': 'No allergen categories documented for this meal.',
      'nutrition_per_serving': 'Nutrition per serving',
      'carbs': 'Carbs',
      'fat': 'Fat',
      'folate': 'Folate',
      'fiber': 'Fiber',
      'ingredients': 'Ingredients',
      'food_safety': 'Food safety notes',
      'cautions': 'Cautions',
      'about_this_info': 'About this information',
      'source': 'Source',
      'not_documented': 'Not documented',
      'content_version': 'Content version',
      'review_status': 'Review status',
      'consent_title': 'Before we begin',
      'consent_body': 'AlmaDiet organizes nutrition information and meal ideas. It does not diagnose, treat, or replace your doctor or midwife. Your health entries stay in your account and are used to filter meal suggestions for safety.',
      'consent_privacy': 'You can export or delete your data anytime from your profile.',
      'consent_agree': 'I understand and agree',
      'my_data': 'My data',
      'export_data': 'Export my data',
      'export_ready': 'Export saved',
      'delete_account': 'Delete account',
      'delete_account_title': 'Delete your account?',
      'delete_account_msg': 'This permanently removes your account, health records, and meal plans. This cannot be undone.',
      'delete_confirm': 'Delete forever',
    },
    'ml': {
      'profile_completion_title': 'പ്രൊഫൈൽ പൂർത്തിയാക്കുക',
      'profile_completion_hint': 'ഗർഭധാരണത്തിന് മുൻപുള്ള BMI-യും ഗർഭ വാരവും സെർവറിൽ കണക്കാക്കുന്നു.',
      'server_calculated_note': 'സെർവറിൽ നിങ്ങൾക്കായി കണക്കാക്കിയത് (വെറും വിവരം)',
      'pre_pregnancy_bmi': 'ഗർഭധാരണത്തിന് മുൻപുള്ള BMI',
      'pregnancy_week': 'വാരം',
      'height_cm_label': 'ഉയരം (സെ.മീ)',
      'height_cm_hint': 'ഉദാ. 160',
      'prepreg_weight_label': 'ഗർഭധാരണത്തിന് മുൻപുള്ള ഭാരം (കി.ഗ്രാം)',
      'prepreg_weight_hint': 'ഗർഭധാരണത്തിന് മുൻപുള്ള നിങ്ങളുടെ ഭാരം',
      'lmp_date_label': 'അവസാന ആർത്തവത്തിന്റെ ആദ്യ ദിവസം',
      'lmp_date_hint': 'തീയതി തിരഞ്ഞെടുക്കാൻ ടാപ്പ് ചെയ്യുക',
      'allergies_label': 'അലർജികൾ — ഇവ അടങ്ങിയ ഭക്ഷണങ്ങൾ എപ്പോഴും ഒഴിവാക്കുന്നു',
      'cooking_time_label': 'പാചക സമയ മുൻഗണന',
      'budget_label': 'ബജറ്റ് മുൻഗണന',
      'dislikes_label': 'ഇഷ്ടപ്പെടാത്ത ചേരുവകൾ',
      'dislikes_hint': 'ഉദാ. കുമ്മിളം',
      'save_and_continue': 'സേവ് ചെയ്ത് തുടരുക',
      'profile_saved_incomplete': 'സേവ് ചെയ്തു — ചില ആവശ്യ വിവരങ്ങൾ ഇപ്പോഴും ബാക്കിയാണ്.',
      'err_enter_height_weight': 'ദയവായി ഉയരവും ഗർഭധാരണത്തിന് മുൻപുള്ള ഭാരവും നൽകുക.',
      'profile_incomplete_title': 'കുറച്ച് വിവരങ്ങൾ വേണം',
      'profile_incomplete_msg': 'വ്യക്തിഗത ഭക്ഷണ നിർദ്ദേശങ്ങൾക്ക് ഉയരം, ഗർഭധാരണത്തിന് മുൻപുള്ള ഭാരം, ഗർഭ തീയതി എന്നിവ വേണം.',
      'complete_profile': 'പ്രൊഫൈൽ പൂർത്തിയാക്കുക',
      'clinician_review_title': 'ഡോക്ടറുടെ നിർദ്ദേശം ശുപാർശ ചെയ്യുന്നു',
      'clinician_review_msg': 'വ്യക്തിഗത ഭക്ഷണ നിർദ്ദേശങ്ങൾക്ക് മുൻപ് ഡോക്ടറുടെ നേരിട്ടുള്ള നിർദ്ദേശം വേണം.',
      'no_safe_suggestion_title': 'ഇപ്പോൾ സുരക്ഷിത നിർദ്ദേശങ്ങളില്ല',
      'no_safe_suggestion_msg': 'നിങ്ങളുടെ സുരക്ഷാ പ്രൊഫൈലുമായി പൊരുത്തപ്പെടുന്ന ഭക്ഷണങ്ങളില്ല. ദയവായി ഡോക്ടറെയോ ഡയറ്റീഷ്യനെയോ സമീപിക്കുക.',
      'consent_required_diet_msg': 'വ്യക്തിഗത നിർദ്ദേശങ്ങൾക്ക് മുൻപ് സമ്മത സ്ക്രീൻ കാണുക.',
      'review_consent': 'സമ്മതം കാണുക',
      'suggested_based_on': 'നിങ്ങളുടെ മുൻഗണനകളും അവലോകനം ചെയ്ത ഭക്ഷണ വിവരങ്ങളും അടിസ്ഥാനമാക്കിയുള്ളത്.',
      'filtered_using': 'നിങ്ങളുടെ അലർജി, ഭക്ഷണ ക്രമീകരണങ്ങൾ ഉപയോഗിച്ച് ഫിൽട്ടർ ചെയ്തത്.',

      'app_name': 'അൽമഡയറ്റ്',
      'welcome': 'അൽമഡയറ്റിലേക്ക് സ്വാഗതം',
      'subtitle': 'നിങ്ങളുടെ ഭാഷയിൽ ഗർഭകാല പോഷണ പിന്തുണ',
      'login': 'ലോഗിൻ',
      'sign_in': 'സൈൻ ഇൻ',
      'register': 'രജിസ്റ്റർ',
      'create_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'email': 'ഇമെയിൽ',
      'password': 'പാസ്‌വേഡ്',
      'name': 'പൂർണ്ണ നാമം',
      'phone': 'ഫോൺ നമ്പർ',
      'home': 'ഹോം',
      'diet_plan': 'ഡയറ്റ് പ്ലാൻ',
      'diet': 'ഭക്ഷണം',
      'urgent_help': 'അടിയന്തര സഹായം',
      'emergency_help': 'അടിയന്തര\nസഹായം',
      'profile': 'പ്രൊഫൈൽ',
      'health_input': 'ആരോഗ്യ ഡാറ്റ',
      'generate_plan': 'ഭക്ഷണ ആശയങ്ങൾ നേടുക',
      'trimester': 'ത്രൈമാസം',
      'week': 'ആഴ്ച',
      'breakfast': 'പ്രഭാതഭക്ഷണം',
      'lunch': 'ഉച്ചഭക്ഷണം',
      'dinner': 'അത്താഴം',
      'snacks': 'ലഘുഭക്ഷണം',
      'calories': 'കലോറി',
      'protein': 'പ്രോട്ടീൻ',
      'iron': 'ഇരുമ്പ്',
      'calcium': 'കാൽസ്യം',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'language': 'ഭാഷ',
      'logout': 'ലോഗൗട്ട്',
      'weight': 'ഭാരം (കി.ഗ്രാം)',
      'hemoglobin': 'ഹീമോഗ്ലോബിൻ (ഗ്രാം/ഡെ.ലി)',
      'blood_sugar': 'രക്തത്തിലെ പഞ്ചസാര (മി.ഗ്രാം/ഡെ.ലി)',
      'blood_pressure': 'രക്തസമ്മർദ്ദം',
      'submit': 'സമർപ്പിക്കുക',
      'get_started': 'ആരംഭിക്കൂ',
      'next': 'അടുത്തത്',
      'skip': 'ഒഴിവാക്കുക',
      'welcome_back': 'വീണ്ടും സ്വാഗതം',
      'sign_in_continue': 'തുടരാൻ സൈൻ ഇൻ ചെയ്യൂ',
      'no_account': 'അക്കൗണ്ട് ഇല്ലേ? ',
      'has_account': 'ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ? ',
      'start_journey': 'നിങ്ങളുടെ ഗർഭകാല പോഷണം ക്രമീകരിക്കുക',
      'hello': 'ഹലോ',
      'companion': 'നിങ്ങളുടെ ഗർഭകാല പോഷണ സഹായി',
      'daily_tip': 'ദൈനംദിന നിർദ്ദേശം',
      'health_input_label': 'ആരോഗ്യ\nഇൻപുട്ട്',
      'my_diet_plan': 'എന്റെ ഭക്ഷണ\nആശയങ്ങൾ',
      'latest_health': 'ഏറ്റവും പുതിയ ആരോഗ്യ ഡാറ്റ',
      'todays_meals': 'ഇന്നത്തെ ഭക്ഷണ ആശയങ്ങൾ',
      'no_plan_yet': 'ഇതുവരെ ഭക്ഷണ ആശയങ്ങളില്ല',
      'no_plan_desc': 'നിങ്ങളുടെ മുൻഗണനകൾക്ക് അനുസൃതമായ ഭക്ഷണ ആശയങ്ങൾക്കായി ആരോഗ്യ ഡാറ്റ സമർപ്പിക്കുക',
      'start_now': 'ഇപ്പോൾ ആരംഭിക്കൂ',
      'loading_dashboard': 'ഡാഷ്ബോർഡ് ലോഡ് ചെയ്യുന്നു...',
      'loading_meal_plan': 'ഭക്ഷണ ആശയങ്ങൾ ലോഡ് ചെയ്യുന്നു...',
      'no_diet_plan': 'ഭക്ഷണ പദ്ധതി ഇല്ല',
      'no_diet_desc': 'ഈ ആഴ്ചയുടെ ഭക്ഷണ ആശയങ്ങൾക്കായി ആദ്യം നിങ്ങളുടെ ആരോഗ്യ ഡാറ്റ സമർപ്പിക്കുക',
      'add_health_data': 'ആരോഗ്യ ഡാറ്റ ചേർക്കുക',
      'daily_targets': 'റഫറൻസ് മൂല്യങ്ങൾ',
      'dietary_alerts': 'സുരക്ഷാ കുറിപ്പുകൾ',
      'pregnancy_info': 'ഗർഭ വിവരങ്ങൾ',
      'health_vitals': 'ആരോഗ്യ സൂചകങ്ങൾ',
      'dietary_pref': 'ഭക്ഷണ മുൻഗണന',
      'bp_systolic': 'ബി.പി. സിസ്റ്റോളിക്',
      'bp_diastolic': 'ബി.പി. ഡയസ്റ്റോളിക്',
      'fasting_sugar': 'നോമ്പു രക്തപഞ്ചസാര',
      'auto_generate': 'സേവ് ചെയ്തതിനുശേഷം ഭക്ഷണ ആശയങ്ങൾ',
      'generate_after': 'ഡാറ്റ സേവ് ചെയ്തുകഴിഞ്ഞാൽ ഒരാഴ്ചത്തെ ഭക്ഷണ ആശയങ്ങൾ',
      'submit_generate': 'സേവ് ചെയ്യുക & ആശയങ്ങൾ',
      'health_tip': 'നിങ്ങളുടെ വിവരങ്ങൾ സുരക്ഷിത ഭക്ഷണ ആശയങ്ങൾ ക്രമീകരിക്കാൻ സഹായിക്കുന്നു. ഇത് രോഗനിർണയത്തിന് ഉപയോഗിക്കുന്നില്ല.',
      'health_submitted': 'ആരോഗ്യ ഡാറ്റ സേവ് ചെയ്തു! ഭക്ഷണ ആശയങ്ങൾ തയ്യാർ.',
      'health_failed': 'നിങ്ങളുടെ ഡാറ്റ സേവ് ചെയ്യാനായില്ല',
      'fix_errors_first': 'തിരിച്ചറിഞ്ഞ ഫീൽഡുകൾ ആദ്യം ശരിയാക്കുക.',
      'err_must_be_number': 'ഒരു സംഖ്യ ആയിരിക്കണം',
      'err_must_be_between': '{min} ഉം {max} ഉം ഇടയിൽ ആയിരിക്കണം',
      'vital_hint_weight': 'സാധാരണ പരിധി: 30–200 കി.ഗ്രാം',
      'vital_hint_hemoglobin': 'സാധാരണ പരിധി: 3–20 ഗ്രാം/ഡെ.ലി',
      'vital_hint_bp_sys': 'സാധാരണ പരിധി: 60–250 mmHg',
      'vital_hint_bp_dia': 'സാധാരണ പരിധി: 40–150 mmHg',
      'vital_hint_sugar': 'സാധാരണ പരിധി: 20–600 മി.ഗ്രാം/ഡെ.ലി',
      'region': 'പ്രദേശം',
      'age': 'പ്രായം',
      'height': 'ഉയരം',
      'pre_weight': 'ഗർഭധാരണത്തിനു മുൻപുള്ള ഭാരം',
      'edit_profile': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      'save_changes': 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
      'profile_updated': 'പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്തു!',
      'profile_photo': 'പ്രൊഫൈൽ ഫോട്ടോ',
      'camera': 'ക്യാമറ',
      'gallery': 'ഗാലറി',
      'remove': 'നീക്കം ചെയ്യുക',
      'exit_title': 'അൽമഡയറ്റ് ഉപേക്ഷിക്കണോ?',
      'exit_msg': 'നിങ്ങൾക്ക് സ്വയം ശ്രദ്ധ നൽകൂ!\nനിങ്ങൾക്ക് ഉറപ്പാണോ?',
      'stay': 'തുടരുക',
      'exit': 'പുറത്തുപോകുക',
      'page_not_found': 'പേജ് കണ്ടെത്തിയില്ല',
      'go_home': 'ഹോമിലേക്ക്',
      'non_veg': 'മാംസാഹാരം',
      'veg': 'സസ്യാഹാരം',
      'eggetarian': 'മുട്ടാഹാരം',
      'first': 'ഒന്നാമത്തെ',
      'second': 'രണ്ടാമത്തെ',
      'third': 'മൂന്നാമത്തെ',
      'onboard_1_title': 'രണ്ടുപേർക്ക് നന്നായി കഴിക്കൂ',
      'onboard_1_desc': 'ഗർഭകാലത്തിലെ ഓരോ ത്രൈമാസത്തിനുമായി ദക്ഷിണ ഇന്ത്യൻ ഭക്ഷണ ആശയങ്ങൾ ക്രമീകരിക്കുക.',
      'onboard_2_title': 'വ്യക്തവും സുരക്ഷിതവുമായ നിർദ്ദേശങ്ങൾ',
      'onboard_2_desc': 'ഭക്ഷണ ആശയങ്ങൾ നിങ്ങളുടെ അലർജികൾ, മുൻഗണനകൾ, ത്രൈമാസം എന്നിവ പാലിക്കുന്നു — ഓരോ നിർദ്ദേശത്തിനും കാരണം കാണിക്കുന്നു.',
      'onboard_3_title': 'പ്രാദേശിക & ബഹുഭാഷ',
      'onboard_3_desc': 'കേരളം, തമിഴ്‌നാട്, കർണാടക, ആന്ധ്ര — നിങ്ങളുടെ ഭാഷയിലും പ്രദേശത്തുനിന്നുമുള്ള ഭക്ഷണം.',
      'analyzing': 'ആരോഗ്യ ഡാറ്റ സേവ് ചെയ്യുന്നു\nഭക്ഷണ ആശയങ്ങൾ തയ്യാറാക്കുന്നു...',
      'loading': 'ലോഡ് ചെയ്യുന്നു...',
      'error_generic': 'എന്തോ തെറ്റായി. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
      'retry': 'വീണ്ടും ശ്രമിക്കുക',
      'urgent_note_title': 'ഡോക്ടർക്കുള്ള കുറിപ്പ്',
      'urgent_note_hint': 'നിങ്ങൾക്ക് എന്ത് അനുഭവപ്പെടുന്നു, എപ്പോൾ തുടങ്ങി, എത്ര തവണ എന്ന് വിവരിക്കുക...',
      'save_note': 'കുറിപ്പ് സേവ് ചെയ്യുക',
      'note_saved': 'കുറിപ്പ് സേവ് ചെയ്തു. ഡോക്ടറുമായി പങ്കിടുക.',
      'add_note': 'കുറിപ്പ് ചേർക്കുക',
      'urgent_app_cannot': 'ഈ ആപ്പിന് അടിയന്തരാവസ്ഥ വിലയിരുത്താനാകില്ല',
      'urgent_disclaimer_fallback': 'അൽമഡയറ്റിന് അടിയന്തരാവസ്ഥകളോ ഉടനടിയുള്ള ലക്ഷണങ്ങളോ വിലയിരുത്താനാകില്ല. ഈ സ്ക്രീൻ സുരക്ഷാ വിവരങ്ങൾ മാത്രം നൽകുന്നു; ഇത് വൈദ്യസലഹമല്ല.',
      'urgent_warning_signs': 'മുന്നറിയിപ്പ് ലക്ഷണങ്ങൾ — വൈദ്യസഹായം തേടുക',
      'urgent_contacts': 'ആരെ ബന്ധപ്പെടണം',
      'emergency_number': 'അടിയന്തരം',
      'ambulance_number': 'ആംബുലൻസ്',
      'urgent_clinician_checklist': 'ഡോക്ടറെ വിളിക്കും മുൻപ്',
      'your_notes': 'നിങ്ങളുടെ കുറിപ്പുകൾ',
      'vitals_optional': 'എല്ലാ ഫീൽഡുകളും ഓപ്ഷണൽ — അറിയാത്തത് ഒഴിവാക്കുക. ഒന്നും ഊഹിക്കില്ല.',
      'allergies': 'അലർജികൾ',
      'allergies_hint': 'ഇവിടെ നൽകിയ ഭക്ഷണങ്ങൾ എല്ലാ ഭക്ഷണ നിർദ്ദേശങ്ങളിൽ നിന്നും പൂർണ്ണമായി ഒഴിവാക്കപ്പെടും.',
      'allergy_placeholder': 'ഉദാ. നിലക്കടയ, മുട്ട, ചെമ്മീൻ...',
      'add_allergy': 'അലർജി ചേർക്കുക',
      'swap_meal': 'ഭക്ഷണം മാറ്റുക',
      'swap_done': 'ഭക്ഷണം മാറ്റി — സുരക്ഷാ ഫിൽട്ടറുകൾ വീണ്ടും പ്രയോഗിച്ചു.',
      'why_suggested': 'നിർദ്ദേശിച്ചത്',
      'reference_only': 'റഫറൻസ് മൂല്യങ്ങൾ മാത്രം — നിർദ്ദേശമല്ല. ലക്ഷ്യങ്ങളെക്കുറിച്ച് ഡോക്ടറുമായി ചർച്ച ചെയ്യുക.',
      'day': 'ദിവസം',
      'today_badge': 'ഇന്ന്',
      'allergens_section': 'അലർജി വിഭാഗങ്ങൾ',
      'no_known_allergens': 'ഈ ഭക്ഷണത്തിന് രേഖപ്പെടുത്തിയ അലർജി വിഭാഗങ്ങളില്ല.',
      'nutrition_per_serving': 'ഒരു സർവിംഗിലെ പോഷകങ്ങൾ',
      'carbs': 'കാർബോഹൈഡ്രേറ്റ്',
      'fat': 'കൊഴുപ്പ്',
      'folate': 'ഫോളേറ്റ്',
      'fiber': 'നാരുകൾ',
      'ingredients': 'ചേരുവകൾ',
      'food_safety': 'ഭക്ഷണ സുരക്ഷാ കുറിപ്പുകൾ',
      'cautions': 'ജാഗ്രതകൾ',
      'about_this_info': 'ഈ വിവരത്തെക്കുറിച്ച്',
      'source': 'ഉറവിടം',
      'not_documented': 'രേഖപ്പെടുത്തിയിട്ടില്ല',
      'content_version': 'ഉള്ളടക്ക പതിപ്പ്',
      'review_status': 'അവലോകന നില',
      'consent_title': 'തുടങ്ങും മുൻപ്',
      'consent_body': 'അൽമഡയറ്റ് പോഷണ വിവരങ്ങളും ഭക്ഷണ ആശയങ്ങളും ക്രമീകരിക്കുന്നു. ഇത് രോഗനിർണയം ചെയ്യുകയോ ചികിത്സിക്കുകയോ ചെയ്യുന്നില്ല; നിങ്ങളുടെ ഡോക്ടറെയോ നഴ്സിനെയോ മാറ്റിനിൽക്കുന്നില്ല. നിങ്ങളുടെ ആരോഗ്യ വിവരങ്ങൾ നിങ്ങളുടെ അക്കൗണ്ടിൽ തന്നെ തുടരും, സുരക്ഷയ്ക്കായി ഭക്ഷണ നിർദ്ദേശങ്ങൾ ഫിൽട്ടർ ചെയ്യാൻ ഉപയോഗിക്കുന്നു.',
      'consent_privacy': 'പ്രൊഫൈലിൽ നിന്ന് എപ്പോൾ വേണമെങ്കിലും ഡാറ്റ എക്സ്പോർട്ട് ചെയ്യാം അല്ലെങ്കിൽ ഇല്ലാതാക്കാം.',
      'consent_agree': 'മനസ്സിലാക്കി; സമ്മതിക്കുന്നു',
      'my_data': 'എന്റെ ഡാറ്റ',
      'export_data': 'ഡാറ്റ എക്സ്പോർട്ട് ചെയ്യുക',
      'export_ready': 'എക്സ്പോർട്ട് സേവ് ചെയ്തു',
      'delete_account': 'അക്കൗണ്ട് ഇല്ലാതാക്കുക',
      'delete_account_title': 'അക്കൗണ്ട് ഇല്ലാതാക്കണോ?',
      'delete_account_msg': 'ഇത് നിങ്ങളുടെ അക്കൗണ്ട്, ആരോഗ്യ രേഖകൾ, ഭക്ഷണ പദ്ധതികൾ ശാശ്വതമായി നീക്കം ചെയ്യുന്നു. ഇത് പിന്നീട് പണിമുടക്കാനാകില്ല.',
      'delete_confirm': 'ശാശ്വതമായി ഇല്ലാതാക്കുക',
    },
    'ta': {
      'profile_completion_title': 'சுயவிவரத்தை முடிக்கவும்',
      'profile_completion_hint': 'கர்ப்பத்திற்கு முந்தைய BMI மற்றும் கர்ப்ப வாரம் சர்வரில் கணக்கிடப்படுகிறது.',
      'server_calculated_note': 'சர்வரில் உங்களுக்காக கணக்கிடப்பட்டது (தகவல் மட்டும்)',
      'pre_pregnancy_bmi': 'கர்ப்பத்திற்கு முந்தைய BMI',
      'pregnancy_week': 'வாரம்',
      'height_cm_label': 'உயரம் (செ.மீ)',
      'height_cm_hint': 'எ.கா. 160',
      'prepreg_weight_label': 'கர்ப்பத்திற்கு முந்தைய எடை (கிலோ)',
      'prepreg_weight_hint': 'கர்ப்பத்திற்கு முன் உங்கள் எடை',
      'lmp_date_label': 'கடைசி மாதவிடாயின் முதல் நாள்',
      'lmp_date_hint': 'தேதியைத் தேர்ந்தெடுக்க தட்டவும்',
      'allergies_label': 'ஒவ்வாமைகள் — இவற்றைக் கொண்ட உணவுகள் எப்போதும் விலக்கப்படும்',
      'cooking_time_label': 'சமையல் நேர விருப்பம்',
      'budget_label': 'பட்ஜெட் விருப்பம்',
      'dislikes_label': 'விருப்பமில்லாத பொருட்கள்',
      'dislikes_hint': 'எ.கா. காளான்',
      'save_and_continue': 'சேமித்து தொடரவும்',
      'profile_saved_incomplete': 'சேமிக்கப்பட்டது — சில தேவையான விவரங்கள் இன்னும் இல்லை.',
      'err_enter_height_weight': 'உயரம் மற்றும் கர்ப்பத்திற்கு முந்தைய எடையை உள்ளிடவும்.',
      'profile_incomplete_title': 'சில விவரங்கள் தேவை',
      'profile_incomplete_msg': 'தனிப்பயன் உணவு பரிந்துரைகளுக்கு உயரம், கர்ப்பத்திற்கு முந்தைய எடை, கர்ப்ப தேதி தேவை.',
      'complete_profile': 'சுயவிவரத்தை முடிக்கவும்',
      'clinician_review_title': 'மருத்துவர் வழிகாட்டுதல் பரிந்துரைக்கப்படுகிறது',
      'clinician_review_msg': 'தனிப்பயன் உணவு பரிந்துரைகளுக்கு முன் மருத்துவரின் நேரடி வழிகாட்டுதல் தேவை.',
      'no_safe_suggestion_title': 'இப்போது பாதுகாப்பான பரிந்துரைகள் இல்லை',
      'no_safe_suggestion_msg': 'உங்கள் பாதுகாப்பு சுயவிவரத்துடன் பொருந்தும் உணவுகள் இல்லை. மருத்துவரை அணுகவும்.',
      'consent_required_diet_msg': 'தனிப்பயன் பரிந்துரைகளுக்கு முன் சம்மதத் திரையைப் பாருங்கள்.',
      'review_consent': 'சம்மதத்தைப் பார்க்கவும்',
      'suggested_based_on': 'உங்கள் விருப்பங்கள் மற்றும் மதிப்பாய்வு செய்யப்பட்ட உணவு உள்ளடக்கத்தின் அடிப்படையில்.',
      'filtered_using': 'உங்கள் ஒவ்வாமை மற்றும் உணவு அமைப்புகளைப் பயன்படுத்தி வடிகட்டப்பட்டது.',

      'app_name': 'அல்மாடயட்',
      'welcome': 'அல்மாடயட்டுக்கு வரவேற்கிறோம்',
      'subtitle': 'உங்கள் மொழியில் கர்ப்பகால ஊட்டச்சத்து ஆதரவு',
      'login': 'உள்நுழைவு',
      'sign_in': 'உள்நுழை',
      'register': 'பதிவு',
      'create_account': 'கணக்கை உருவாக்கு',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'name': 'முழு பெயர்',
      'phone': 'தொலைபேசி எண்',
      'home': 'முகப்பு',
      'diet_plan': 'உணவுத் திட்டம்',
      'diet': 'உணவு',
      'urgent_help': 'அவசர உதவி',
      'emergency_help': 'அவசர\nஉதவி',
      'profile': 'சுயவிவரம்',
      'health_input': 'சுகாதார தரவு',
      'generate_plan': 'உணவு யோசனைகளைப் பெறுங்கள்',
      'trimester': 'மூன்று மாத காலம்',
      'week': 'வாரம்',
      'breakfast': 'காலை உணவு',
      'lunch': 'மதிய உணவு',
      'dinner': 'இரவு உணவு',
      'snacks': 'சிற்றுண்டி',
      'calories': 'கலோரிகள்',
      'protein': 'புரதம்',
      'iron': 'இரும்பு',
      'calcium': 'கால்சியம்',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'logout': 'வெளியேறு',
      'weight': 'எடை (கிலோ)',
      'hemoglobin': 'ஹீமோகுளோபின் (கிராம்/டெ.லி)',
      'blood_sugar': 'இரத்த சர்க்கரை (மி.கி/டெ.லி)',
      'blood_pressure': 'இரத்த அழுத்தம்',
      'submit': 'சமர்ப்பி',
      'get_started': 'தொடங்குங்கள்',
      'next': 'அடுத்து',
      'skip': 'தவிர்',
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'sign_in_continue': 'தொடர உள்நுழையுங்கள்',
      'no_account': 'கணக்கு இல்லையா? ',
      'has_account': 'ஏற்கனவே கணக்கு உள்ளதா? ',
      'start_journey': 'உங்கள் கர்ப்பகால ஊட்டச்சத்தை ஒழுங்கமைக்கவும்',
      'hello': 'வணக்கம்',
      'companion': 'உங்கள் கர்ப்பகால ஊட்டச்சத்து துணை',
      'daily_tip': 'தினசரி குறிப்பு',
      'health_input_label': 'சுகாதார\nஉள்ளீடு',
      'my_diet_plan': 'என் உணவு\nயோசனைகள்',
      'latest_health': 'சமீபத்திய சுகாதார தரவு',
      'todays_meals': 'இன்றைய உணவு யோசனைகள்',
      'no_plan_yet': 'இன்னும் உணவு யோசனைகள் இல்லை',
      'no_plan_desc': 'உங்கள் விருப்பங்களுக்கு ஏற்ற உணவு யோசனைகளுக்கு உங்கள் சுகாதார தரவை சமர்ப்பிக்கவும்',
      'start_now': 'இப்போது தொடங்குங்கள்',
      'loading_dashboard': 'டாஷ்போர்டை ஏற்றுகிறது...',
      'loading_meal_plan': 'உணவு யோசனைகளை ஏற்றுகிறது...',
      'no_diet_plan': 'உணவு திட்டம் இல்லை',
      'no_diet_desc': 'இந்த வாரத்தின் உணவு யோசனைகளுக்கு முதலில் உங்கள் சுகாதார தரவை சமர்ப்பிக்கவும்',
      'add_health_data': 'சுகாதார தரவைச் சேர்க்கவும்',
      'daily_targets': 'குறிப்பு மதிப்புகள்',
      'dietary_alerts': 'பாதுகாப்பு குறிப்புகள்',
      'pregnancy_info': 'கர்ப்ப தகவல்',
      'health_vitals': 'சுகாதார அளவீடுகள்',
      'dietary_pref': 'உணவு விருப்பம்',
      'bp_systolic': 'ரத்த அழுத்தம் சிஸ்டாலிக்',
      'bp_diastolic': 'ரத்த அழுத்தம் டயஸ்டாலிக்',
      'fasting_sugar': 'விரத இரத்த சர்க்கரை',
      'auto_generate': 'சேமித்த பிறகு உணவு யோசனைகள்',
      'generate_after': 'தரவு சேமிக்கப்பட்டதும் ஒரு வார உணவு யோசனைகள்',
      'submit_generate': 'சேமி & யோசனைகள்',
      'health_tip': 'பாதுகாப்பான உணவு யோசனைகளை ஒழுங்கமைக்க உங்கள் தகவல் உதவுகிறது. இது நோய் கண்டறிய பயன்படுத்தப்படாது.',
      'health_submitted': 'சுகாதார தரவு சேமிக்கப்பட்டது! உணவு யோசனைகள் தயார்.',
      'health_failed': 'உங்கள் தரவை சேமிக்க முடியவில்லை',
      'fix_errors_first': 'சுட்டிக்காட்டப்பட்ட புலங்களை முதலில் சரிசெய்யவும்.',
      'err_must_be_number': 'எண்ணாக இருக்க வேண்டும்',
      'err_must_be_between': '{min} மற்றும் {max} இடையே இருக்க வேண்டும்',
      'vital_hint_weight': 'வழக்கமான வரம்பு: 30–200 கிலோ',
      'vital_hint_hemoglobin': 'வழக்கமான வரம்பு: 3–20 கிராம்/டெ.லி',
      'vital_hint_bp_sys': 'வழக்கமான வரம்பு: 60–250 mmHg',
      'vital_hint_bp_dia': 'வழக்கமான வரம்பு: 40–150 mmHg',
      'vital_hint_sugar': 'வழக்கமான வரம்பு: 20–600 மி.கிரா/டெ.லி',
      'region': 'பகுதி',
      'age': 'வயது',
      'height': 'உயரம்',
      'pre_weight': 'கர்ப்பத்திற்கு முந்தைய எடை',
      'edit_profile': 'சுயவிவரத்தை திருத்து',
      'save_changes': 'மாற்றங்களை சேமி',
      'profile_updated': 'சுயவிவரம் புதுப்பிக்கப்பட்டது!',
      'profile_photo': 'சுயவிவரப் படம்',
      'camera': 'கேமரா',
      'gallery': 'கால்வாய்',
      'remove': 'அகற்று',
      'exit_title': 'அல்மாடயட்டை விட்டு வெளியேறவா?',
      'exit_msg': 'உங்களை நீங்களே கவனித்துக் கொள்ளுங்கள்!\nவெளியேற உறுதியா?',
      'stay': 'தங்கு',
      'exit': 'வெளியேறு',
      'page_not_found': 'பக்கம் கிடைக்கவில்லை',
      'go_home': 'முகப்புக்குச் செல்',
      'non_veg': 'அசைவம்',
      'veg': 'சைவம்',
      'eggetarian': 'முட்டை உணவு',
      'first': 'முதல்',
      'second': 'இரண்டாம்',
      'third': 'மூன்றாம்',
      'onboard_1_title': 'இரண்டு பேருக்கும் நல்லா சாப்பிடுங்கள்',
      'onboard_1_desc': 'கர்ப்பத்தின் ஒவ்வொரு மூன்று மாத காலத்திற்கும் தென்னிந்திய உணவு யோசனைகளை ஒழுங்கமைக்கவும்.',
      'onboard_2_title': 'தெளிவான, பாதுகாப்பான பரிந்துரைகள்',
      'onboard_2_desc': 'உணவு யோசனைகள் உங்கள் ஒவ்வாமை, விருப்பங்கள், கர்ப்ப காலத்தை மதிக்கின்றன — ஒவ்வொரு பரிந்துரைக்கும் காரணம் காட்டப்படும்.',
      'onboard_3_title': 'பிராந்திய & பன்மொழி',
      'onboard_3_desc': 'கேரளா, தமிழ்நாடு, கர்நாடகா, ஆந்திரா — உங்கள் மொழியிலும் பகுதியிலிருந்தும் உணவுகள்.',
      'analyzing': 'சுகாதார தரவை சேமிக்கிறது\nஉணவு யோசனைகளை தயார் செய்கிறது...',
      'loading': 'ஏற்றுகிறது...',
      'error_generic': 'ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
      'retry': 'மீண்டும் முயற்சி',
      'urgent_note_title': 'மருத்துவருக்கான குறிப்பு',
      'urgent_note_hint': 'என்ன உணர்கிறீர்கள், எப்போது தொடங்கியது, எவ்வளவு முறை என்று விவரிக்கவும்...',
      'save_note': 'குறிப்பை சேமி',
      'note_saved': 'குறிப்பு சேமிக்கப்பட்டது. மருத்துவருடன் பகிரவும்.',
      'add_note': 'குறிப்பு சேர்',
      'urgent_app_cannot': 'இந்த செயலியால் அவசரநிலையை மதிப்பிட முடியாது',
      'urgent_disclaimer_fallback': 'அல்மாடயட்டால் அவசரநிலைகளையோ உடனடி அறிகுறிகளையோ மதிப்பிட முடியாது. இந்தத் திரை பாதுகாப்பு தகவலை மட்டுமே வழங்குகிறது; இது மருத்துவ ஆலோசனை அல்ல.',
      'urgent_warning_signs': 'எச்சரிக்கை அறிகுறிகள் — மருத்துவ உதவி பெறுங்கள்',
      'urgent_contacts': 'யாரைத் தொடர்பு கொள்ள வேண்டும்',
      'emergency_number': 'அவசரம்',
      'ambulance_number': 'ஆம்புலன்ஸ்',
      'urgent_clinician_checklist': 'மருத்துவரை அழைப்பதற்கு முன்',
      'your_notes': 'உங்கள் குறிப்புகள்',
      'vitals_optional': 'அனைத்து புலங்களும் விருப்பம் — தெரியாததை விட்டுவிடுங்கள். எதுவும் ஊகிக்கப்படாது.',
      'allergies': 'ஒவ்வாமைகள்',
      'allergies_hint': 'இங்கே பட்டியலிடப்பட்ட உணவுகள் அனைத்து உணவு பரிந்துரைகளிலிருந்தும் முழுமையாக விலக்கப்படும்.',
      'allergy_placeholder': 'எ.கா. நிலக்கடலை, முட்டை, இறால்...',
      'add_allergy': 'ஒவ்வாமை சேர்',
      'swap_meal': 'உணவை மாற்று',
      'swap_done': 'உணவு மாற்றப்பட்டது — பாதுகாப்பு வடிகட்டல்கள் மீண்டும் பயன்படுத்தப்பட்டன.',
      'why_suggested': 'பரிந்துரைக்கப்பட்டது',
      'reference_only': 'குறிப்பு மதிப்புகள் மட்டுமே — பரிந்துரை அல்ல. இலக்குகளை மருத்துவருடன் விவாதிக்கவும்.',
      'day': 'நாள்',
      'today_badge': 'இன்று',
      'allergens_section': 'ஒவ்வாமை வகைகள்',
      'no_known_allergens': 'இந்த உணவுக்கு பதிவு செய்யப்பட்ட ஒவ்வாமை வகைகள் இல்லை.',
      'nutrition_per_serving': 'ஒரு வழங்கலுக்கான ஊட்டச்சத்து',
      'carbs': 'கார்போஹைட்ரேட்',
      'fat': 'கொழுப்பு',
      'folate': 'ஃபோலேட்',
      'fiber': 'நார்ச்சத்து',
      'ingredients': 'மூலப்பொருட்கள்',
      'food_safety': 'உணவு பாதுகாப்பு குறிப்புகள்',
      'cautions': 'எச்சரிக்கைகள்',
      'about_this_info': 'இந்த தகவலைப் பற்றி',
      'source': 'மூலம்',
      'not_documented': 'பதிவு செய்யப்படவில்லை',
      'content_version': 'உள்ளடக்க பதிப்பு',
      'review_status': 'மதிப்பாய்வு நிலை',
      'consent_title': 'தொடங்குவதற்கு முன்',
      'consent_body': 'அல்மாடயட் ஊட்டச்சத்து தகவல் மற்றும் உணவு யோசனைகளை ஒழுங்கமைக்கிறது. இது நோய் கண்டறியவோ சிகிச்சை அளிக்கவோ செய்யாது; உங்கள் மருத்துவரையோ மருத்துவக் கவனிப்பாளரையோ மாற்றாது. உங்கள் சுகாதார தகவல் உங்கள் கணக்கிலேயே இருக்கும், பாதுகாப்பிற்காக உணவு பரிந்துரைகளை வடிகட்ட பயன்படுத்தப்படும்.',
      'consent_privacy': 'உங்கள் சுயவிவரத்திலிருந்து எப்போது வேண்டுமானாலும் தரவை ஏற்றுமதி செய்யலாம் அல்லது நீக்கலாம்.',
      'consent_agree': 'புரிந்தது; சம்மதிக்கிறேன்',
      'my_data': 'என் தரவு',
      'export_data': 'தரவை ஏற்றுமதி செய்',
      'export_ready': 'ஏற்றுமதி சேமிக்கப்பட்டது',
      'delete_account': 'கணக்கை நீக்கு',
      'delete_account_title': 'கணக்கை நீக்கவா?',
      'delete_account_msg': 'இது உங்கள் கணக்கு, சுகாதார பதிவுகள், உணவு திட்டங்களை நிரந்தரமாக நீக்கும். இதை மீட்டெடுக்க முடியாது.',
      'delete_confirm': 'நிரந்தரமாக நீக்கு',
    },
    'kn': {
      'profile_completion_title': 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
      'profile_completion_hint': 'ಗರ್ಭಧಾರಣೆಯ ಮೊದಲ BMI ಮತ್ತು ಗರ್ಭಧಾರಣೆಯ ವಾರ ಸರ್ವರ್‌ನಲ್ಲಿ ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ.',
      'server_calculated_note': 'ಸರ್ವರ್‌ನಲ್ಲಿ ನಿಮಗಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ (ಮಾಹಿತಿ ಮಾತ್ರ)',
      'pre_pregnancy_bmi': 'ಗರ್ಭಧಾರಣೆಯ ಮೊದಲ BMI',
      'pregnancy_week': 'ವಾರ',
      'height_cm_label': 'ಎತ್ತರ (ಸೆಂ.ಮೀ)',
      'height_cm_hint': 'ಉದಾ. 160',
      'prepreg_weight_label': 'ಗರ್ಭಧಾರಣೆಯ ಮೊದಲ ತೂಕ (ಕೆಜಿ)',
      'prepreg_weight_hint': 'ಗರ್ಭಧಾರಣೆಯ ಮೊದಲ ನಿಮ್ಮ ತೂಕ',
      'lmp_date_label': 'ಕೊನೆಯ ಮಾಸಿಕದ ಮೊದಲ ದಿನ',
      'lmp_date_hint': 'ದಿನಾಂಕ ಆಯ್ಕೆ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
      'allergies_label': 'ಅಲರ್ಜಿಗಳು — ಇವುಗಳಿರುವ ಊಟಗಳು ಯಾವಾಗಲೂ ಹೊರಗಿಡಲಾಗುತ್ತದೆ',
      'cooking_time_label': 'ಅಡುಗೆ ಸಮಯ ಆದ್ಯತೆ',
      'budget_label': 'ಬಜೆಟ್ ಆದ್ಯತೆ',
      'dislikes_label': 'ಇಷ್ಟವಿಲ್ಲದ ಪದಾರ್ಥಗಳು',
      'dislikes_hint': 'ಉದಾ. ಮಶ್ರೂಮ್',
      'save_and_continue': 'ಉಳಿಸಿ ಮತ್ತು ಮುಂದುವರಿಸಿ',
      'profile_saved_incomplete': 'ಉಳಿಸಲಾಗಿದೆ — ಕೆಲವು ಅಗತ್ಯ ವಿವರಗಳು ಇನ್ನೂ ಉಳಿದಿವೆ.',
      'err_enter_height_weight': 'ಎತ್ತರ ಮತ್ತು ಗರ್ಭಧಾರಣೆಯ ಮೊದಲ ತೂಕ ನಮೂದಿಸಿ.',
      'profile_incomplete_title': 'ಕೆಲವು ವಿವರಗಳು ಬೇಕು',
      'profile_incomplete_msg': 'ವೈಯಕ್ತಿಕ ಊಟದ ಸಲಹೆಗಳಿಗೆ ಎತ್ತರ, ಗರ್ಭಧಾರಣೆಯ ಮೊದಲ ತೂಕ, ಗರ್ಭಧಾರಣೆಯ ದಿನಾಂಕ ಬೇಕು.',
      'complete_profile': 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
      'clinician_review_title': 'ವೈದ್ಯರ ಮಾರ್ಗದರ್ಶನ ಶಿಫಾರಸು',
      'clinician_review_msg': 'ವೈಯಕ್ತಿಕ ಊಟದ ಸಲಹೆಗಳ ಮೊದಲು ವೈದ್ಯರ ನೇರ ಮಾರ್ಗದರ್ಶನ ಬೇಕು.',
      'no_safe_suggestion_title': 'ಈಗ ಸುರಕ್ಷಿತ ಸಲಹೆಗಳಿಲ್ಲ',
      'no_safe_suggestion_msg': 'ನಿಮ್ಮ ಸುರಕ್ಷತಾ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೊಂದುವ ಊಟಗಳಿಲ್ಲ. ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
      'consent_required_diet_msg': 'ವೈಯಕ್ತಿಕ ಸಲಹೆಗಳ ಮೊದಲು ಸಮ್ಮತಿ ಪರದೆಯನ್ನು ನೋಡಿ.',
      'review_consent': 'ಸಮ್ಮತಿ ನೋಡಿ',
      'suggested_based_on': 'ನಿಮ್ಮ ಆದ್ಯತೆಗಳು ಮತ್ತು ಪರಿಶೀಲಿಸಿದ ಊಟದ ವಿಷಯದ ಆಧಾರದ ಮೇಲೆ.',
      'filtered_using': 'ನಿಮ್ಮ ಅಲರ್ಜಿ ಮತ್ತು ಆಹಾರ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಬಳಸಿ ಫಿಲ್ಟರ್ ಮಾಡಲಾಗಿದೆ.',

      'app_name': 'ಅಲ್ಮಾಡಯಟ್',
      'welcome': 'ಅಲ್ಮಾಡಯಟ್‌ಗೆ ಸ್ವಾಗತ',
      'subtitle': 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಗರ್ಭಾವಸ್ಥೆಯ ಪೋಷಣೆ ಬೆಂಬಲ',
      'login': 'ಲಾಗಿನ್',
      'sign_in': 'ಸೈನ್ ಇನ್',
      'register': 'ನೋಂದಣಿ',
      'create_account': 'ಖಾತೆ ರಚಿಸಿ',
      'email': 'ಇಮೇಲ್',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'name': 'ಪೂರ್ಣ ಹೆಸರು',
      'phone': 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
      'home': 'ಮುಖಪುಟ',
      'diet_plan': 'ಆಹಾರ ಯೋಜನೆ',
      'diet': 'ಆಹಾರ',
      'urgent_help': 'ತುರ್ತು ಸಹಾಯ',
      'emergency_help': 'ತುರ್ತು\nಸಹಾಯ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'health_input': 'ಆರೋಗ್ಯ ಡೇಟಾ',
      'generate_plan': 'ಊಟದ ಸಲಹೆಗಳನ್ನು ಪಡಿ',
      'trimester': 'ಮೂರು ತಿಂಗಳ ಅವಧಿ',
      'week': 'ವಾರ',
      'breakfast': 'ತಿಂಡಿ',
      'lunch': 'ಊಟ',
      'dinner': 'ರಾತ್ರಿ ಊಟ',
      'snacks': 'ತಿಂಡಿ ತಿನಿಸು',
      'calories': 'ಕ್ಯಾಲೊರಿಗಳು',
      'protein': 'ಪ್ರೋಟೀನ್',
      'iron': 'ಕಬ್ಬಿಣ',
      'calcium': 'ಕ್ಯಾಲ್ಸಿಯಮ್',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'language': 'ಭಾಷೆ',
      'logout': 'ಲಾಗ್‌ಔಟ್',
      'weight': 'ತೂಕ (ಕೆಜಿ)',
      'hemoglobin': 'ಹಿಮೋಗ್ಲೋಬಿನ್ (ಗ್ರಾಂ/ಡೆ.ಲಿ)',
      'blood_sugar': 'ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆ (ಮಿ.ಗ್ರಾಂ/ಡೆ.ಲಿ)',
      'blood_pressure': 'ರಕ್ತದೊತ್ತಡ',
      'submit': 'ಸಲ್ಲಿಸು',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'next': 'ಮುಂದೆ',
      'skip': 'ಬಿಟ್ಟುಬಿಡಿ',
      'welcome_back': 'ಮತ್ತೆ ಸ್ವಾಗತ',
      'sign_in_continue': 'ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
      'no_account': 'ಖಾತೆ ಇಲ್ಲವೇ? ',
      'has_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ',
      'start_journey': 'ನಿಮ್ಮ ಗರ್ಭಾವಸ್ಥೆಯ ಪೋಷಣೆಯನ್ನು ವ್ಯವಸ್ಥಿತಗೊಳಿಸಿ',
      'hello': 'ನಮಸ್ಕಾರ',
      'companion': 'ನಿಮ್ಮ ಗರ್ಭಾವಸ್ಥೆಯ ಪೋಷಣೆ ಸಹಚರ',
      'daily_tip': 'ದೈನಂದಿನ ಸಲಹೆ',
      'health_input_label': 'ಆರೋಗ್ಯ\nಇನ್‌ಪುಟ್',
      'my_diet_plan': 'ನನ್ನ ಊಟದ\nಸಲಹೆಗಳು',
      'latest_health': 'ಇತ್ತೀಚಿನ ಆರೋಗ್ಯ ಡೇಟಾ',
      'todays_meals': 'ಇಂದಿನ ಊಟದ ಸಲಹೆಗಳು',
      'no_plan_yet': 'ಇನ್ನೂ ಊಟದ ಸಲಹೆಗಳಿಲ್ಲ',
      'no_plan_desc': 'ನಿಮ್ಮ ಆದ್ಯತೆಗಳಿಗೆ ಅನುಗುಣವಾದ ಊಟದ ಸಲಹೆಗಳಿಗಾಗಿ ಆರೋಗ್ಯ ಡೇಟಾವನ್ನು ಸಲ್ಲಿಸಿ',
      'start_now': 'ಈಗ ಪ್ರಾರಂಭಿಸಿ',
      'loading_dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'loading_meal_plan': 'ಊಟದ ಸಲಹೆಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
      'no_diet_plan': 'ಆಹಾರ ಯೋಜನೆ ಇಲ್ಲ',
      'no_diet_desc': 'ಈ ವಾರದ ಊಟದ ಸಲಹೆಗಳಿಗಾಗಿ ಮೊದಲು ನಿಮ್ಮ ಆರೋಗ್ಯ ಡೇಟಾವನ್ನು ಸಲ್ಲಿಸಿ',
      'add_health_data': 'ಆರೋಗ್ಯ ಡೇಟಾ ಸೇರಿಸಿ',
      'daily_targets': 'ಉಲ್ಲೇಖ ಮೌಲ್ಯಗಳು',
      'dietary_alerts': 'ಸುರಕ್ಷತಾ ಟಿಪ್ಪಣಿಗಳು',
      'pregnancy_info': 'ಗರ್ಭಧಾರಣೆ ಮಾಹಿತಿ',
      'health_vitals': 'ಆರೋಗ್ಯ ಸೂಚಕಗಳು',
      'dietary_pref': 'ಆಹಾರ ಆದ್ಯತೆ',
      'bp_systolic': 'ರಕ್ತದೊತ್ತಡ ಸಿಸ್ಟೊಲಿಕ್',
      'bp_diastolic': 'ರಕ್ತದೊತ್ತಡ ಡಯಾಸ್ಟೊಲಿಕ್',
      'fasting_sugar': 'ಉಪವಾಸ ರಕ್ತಸಕ್ಕರೆ',
      'auto_generate': 'ಉಳಿಸಿದ ನಂತರ ಊಟದ ಸಲಹೆಗಳು',
      'generate_after': 'ಡೇಟಾ ಉಳಿಸಿದ ನಂತರ ಒಂದು ವಾರದ ಊಟದ ಸಲಹೆಗಳು',
      'submit_generate': 'ಉಳಿಸಿ & ಸಲಹೆಗಳು',
      'health_tip': 'ಸುರಕ್ಷಿತ ಊಟದ ಸಲಹೆಗಳನ್ನು ವ್ಯವಸ್ಥಿತಗೊಳಿಸಲು ನಿಮ್ಮ ಮಾಹಿತಿ ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಇದನ್ನು ರೋಗನಿರ್ಣಯಕ್ಕಾಗಿ ಬಳಸಲಾಗುವುದಿಲ್ಲ.',
      'health_submitted': 'ಆರೋಗ್ಯ ಡೇಟಾ ಉಳಿಸಲಾಗಿದೆ! ಊಟದ ಸಲಹೆಗಳು ಸಿದ್ಧ.',
      'health_failed': 'ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಉಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',
      'fix_errors_first': 'ಗುರುತಿಸಿದ ಫೀಲ್ಡ್‌ಗಳನ್ನು ಮೊದಲು ಸರಿಪಡಿಸಿ.',
      'err_must_be_number': 'ಸಂಖ್ಯೆ ಆಗಿರಬೇಕು',
      'err_must_be_between': '{min} ಮತ್ತು {max} ನಡುವೆ ಇರಬೇಕು',
      'vital_hint_weight': 'ಸಾಮಾನ್ಯ ವ್ಯಾಪ್ತಿ: 30–200 ಕೆಜಿ',
      'vital_hint_hemoglobin': 'ಸಾಮಾನ್ಯ ವ್ಯಾಪ್ತಿ: 3–20 ಗ್ರಾಂ/ಡೆ.ಲಿ',
      'vital_hint_bp_sys': 'ಸಾಮಾನ್ಯ ವ್ಯಾಪ್ತಿ: 60–250 mmHg',
      'vital_hint_bp_dia': 'ಸಾಮಾನ್ಯ ವ್ಯಾಪ್ತಿ: 40–150 mmHg',
      'vital_hint_sugar': 'ಸಾಮಾನ್ಯ ವ್ಯಾಪ್ತಿ: 20–600 ಮಿ.ಗ್ರಾಂ/ಡೆ.ಲಿ',
      'region': 'ಪ್ರದೇಶ',
      'age': 'ವಯಸ್ಸು',
      'height': 'ಎತ್ತರ',
      'pre_weight': 'ಗರ್ಭಧಾರಣೆಗೂ ಮೊದಲಿನ ತೂಕ',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      'save_changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
      'profile_updated': 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ!',
      'profile_photo': 'ಪ್ರೊಫೈಲ್ ಫೋಟೋ',
      'camera': 'ಕ್ಯಾಮೆರಾ',
      'gallery': 'ಗ್ಯಾಲರಿ',
      'remove': 'ತೆಗೆದುಹಾಕಿ',
      'exit_title': 'ಅಲ್ಮಾಡಯಟ್ ತೊರೆಯಬೇಕೆ?',
      'exit_msg': 'ನಿಮ್ಮನ್ನು ನೀವು ನೋಡಿಕೊಳ್ಳಿ!\nನಿರ್ಗಮಿಸಲು ಖಚಿತವೇ?',
      'stay': 'ಉಳಿಯಿರಿ',
      'exit': 'ನಿರ್ಗಮಿಸಿ',
      'page_not_found': 'ಪುಟ ಸಿಗಲಿಲ್ಲ',
      'go_home': 'ಮುಖಪುಟಕ್ಕೆ',
      'non_veg': 'ಮಾಂಸಾಹಾರಿ',
      'veg': 'ಶಾಕಾಹಾರಿ',
      'eggetarian': 'ಮೊಟ್ಟೆ ಆಹಾರಿ',
      'first': 'ಮೊದಲನೆಯದು',
      'second': 'ಎರಡನೆಯದು',
      'third': 'ಮೂರನೆಯದು',
      'onboard_1_title': 'ಇಬ್ಬರಿಗಾಗಿ ಚೆನ್ನಾಗಿ ತಿನ್ನಿ',
      'onboard_1_desc': 'ಗರ್ಭಧಾರಣೆಯ ಪ್ರತಿ ಹಂತಕ್ಕೂ ದಕ್ಷಿಣ ಭಾರತದ ಊಟದ ಸಲಹೆಗಳನ್ನು ವ್ಯವಸ್ಥಿತಗೊಳಿಸಿ.',
      'onboard_2_title': 'ಸ್ಪಷ್ಟ, ಸುರಕ್ಷಿತ ಸಲಹೆಗಳು',
      'onboard_2_desc': 'ಊಟದ ಸಲಹೆಗಳು ನಿಮ್ಮ ಅಲರ್ಜಿ, ಆದ್ಯತೆಗಳು, ಗರ್ಭಾವಸ್ಥೆಯ ಹಂತವನ್ನು ಗೌರವಿಸುತ್ತವೆ — ಪ್ರತಿ ಸಲಹೆಗೂ ಕಾರಣ ತೋರಿಸಲಾಗುತ್ತದೆ.',
      'onboard_3_title': 'ಪ್ರಾದೇಶಿಕ & ಬಹುಭಾಷಾ',
      'onboard_3_desc': 'ಕೇರಳ, ತಮಿಳುನಾಡು, ಕರ್ನಾಟಕ, ಆಂಧ್ರ — ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮತ್ತು ನಿಮ್ಮ ಪ್ರದೇಶದ ಊಟ.',
      'analyzing': 'ಆರೋಗ್ಯ ಡೇಟಾ ಉಳಿಸಲಾಗುತ್ತಿದೆ\nಊಟದ ಸಲಹೆಗಳು ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿವೆ...',
      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'error_generic': 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'urgent_note_title': 'ವೈದ್ಯರಿಗೆ ಟಿಪ್ಪಣಿ',
      'urgent_note_hint': 'ನಿಮಗೆ ಏನನ್ನು ಅನುಭವಿಸುತ್ತಿದ್ದೀರಿ, ಯಾವಾಗ ಪ್ರಾರಂಭವಾಯಿತು, ಎಷ್ಟು ಬಾರಿ ಎಂದು ವಿವರಿಸಿ...',
      'save_note': 'ಟಿಪ್ಪಣಿ ಉಳಿಸಿ',
      'note_saved': 'ಟಿಪ್ಪಣಿ ಉಳಿಸಲಾಗಿದೆ. ವೈದ್ಯರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ.',
      'add_note': 'ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ',
      'urgent_app_cannot': 'ಈ ಅಪ್ಲಿಕೇಶನ್ ತುರ್ತು ಪರಿಸ್ಥಿತಿಯನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಲು ಸಾಧ್ಯವಿಲ್ಲ',
      'urgent_disclaimer_fallback': 'ಅಲ್ಮಾಡಯಟ್ ತುರ್ತು ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಅಥವಾ ತಕ್ಷಣದ ಲಕ್ಷಣಗಳನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಲು ಸಾಧ್ಯವಿಲ್ಲ. ಈ ಪರದೆ ಸುರಕ್ಷತಾ ಮಾಹಿತಿಯನ್ನು ಮಾತ್ರ ನೀಡುತ್ತದೆ; ಇದು ವೈದ್ಯಕೀಯ ಸಲಹೆಯಲ್ಲ.',
      'urgent_warning_signs': 'ಎಚ್ಚರಿಕೆ ಚಿಹ್ನೆಗಳು — ವೈದ್ಯಕೀಯ ಸಹಾಯ ಪಡಿ',
      'urgent_contacts': 'ಯಾರನ್ನು ಸಂಪರ್ಕಿಸಬೇಕು',
      'emergency_number': 'ತುರ್ತು',
      'ambulance_number': 'ಆಂಬ್ಯುಲೆನ್ಸ್',
      'urgent_clinician_checklist': 'ವೈದ್ಯರನ್ನು ಕರೆಯುವ ಮೊದಲು',
      'your_notes': 'ನಿಮ್ಮ ಟಿಪ್ಪಣಿಗಳು',
      'vitals_optional': 'ಎಲ್ಲಾ ಫೀಲ್ಡ್‌ಗಳು ಐಚ್ಛಿಕ — ಗೊತ್ತಿಲ್ಲದವುಗಳನ್ನು ಬಿಟ್ಟುಬಿಡಿ. ಏನನ್ನೂ ಊಹಿಸಲಾಗುವುದಿಲ್ಲ.',
      'allergies': 'ಅಲರ್ಜಿಗಳು',
      'allergies_hint': 'ಇಲ್ಲಿ ಪಟ್ಟಿ ಮಾಡಿದ ಆಹಾರಗಳು ಎಲ್ಲಾ ಊಟದ ಸಲಹೆಗಳಿಂದ ಸಂಪೂರ್ಣವಾಗಿ ಹೊರಗಿಡಲ್ಪಡುತ್ತವೆ.',
      'allergy_placeholder': 'ಉದಾ. ಕಡಲೆಕಾಯಿ, ಮೊಟ್ಟೆ, ಸೀಗಡಿ...',
      'add_allergy': 'ಅಲರ್ಜಿ ಸೇರಿಸಿ',
      'swap_meal': 'ಊಟ ಬದಲಿಸಿ',
      'swap_done': 'ಊಟ ಬದಲಾಯಿಸಲಾಗಿದೆ — ಸುರಕ್ಷತಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಮರು-ಅನ್ವಯಿಸಲಾಗಿದೆ.',
      'why_suggested': 'ಸಲಹೆ ನೀಡಿದ ಕಾರಣ',
      'reference_only': 'ಉಲ್ಲೇಖ ಮೌಲ್ಯಗಳು ಮಾತ್ರ — ಸೂಚನೆಯಲ್ಲ. ಗುರಿಗಳ ಬಗ್ಗೆ ವೈದ್ಯರೊಂದಿಗೆ ಚರ್ಚಿಸಿ.',
      'day': 'ದಿನ',
      'today_badge': 'ಇಂದು',
      'allergens_section': 'ಅಲರ್ಜಿ ವರ್ಗಗಳು',
      'no_known_allergens': 'ಈ ಊಟಕ್ಕೆ ದಾಖಲಾದ ಅಲರ್ಜಿ ವರ್ಗಗಳಿಲ್ಲ.',
      'nutrition_per_serving': 'ಒಂದು ಸೇವೆಯಲ್ಲಿನ ಪೋಷಣೆ',
      'carbs': 'ಕಾರ್ಬೋಹೈಡ್ರೇಟ್',
      'fat': 'ಕೊಬ್ಬು',
      'folate': 'ಫೋಲೇಟ್',
      'fiber': 'ಫೈಬರ್',
      'ingredients': 'ಪದಾರ್ಥಗಳು',
      'food_safety': 'ಆಹಾರ ಸುರಕ್ಷತಾ ಟಿಪ್ಪಣಿಗಳು',
      'cautions': 'ಎಚ್ಚರಿಕೆಗಳು',
      'about_this_info': 'ಈ ಮಾಹಿತಿ ಬಗ್ಗೆ',
      'source': 'ಮೂಲ',
      'not_documented': 'ದಾಖಲಾಗಿಲ್ಲ',
      'content_version': 'ವಿಷಯ ಆವೃತ್ತಿ',
      'review_status': 'ವಿಮರ್ಶೆ ಸ್ಥಿತಿ',
      'consent_title': 'ಪ್ರಾರಂಭಿಸುವ ಮೊದಲು',
      'consent_body': 'ಅಲ್ಮಾಡಯಟ್ ಪೋಷಣೆ ಮಾಹಿತಿ ಮತ್ತು ಊಟದ ಸಲಹೆಗಳನ್ನು ವ್ಯವಸ್ಥಿತಗೊಳಿಸುತ್ತದೆ. ಇದು ರೋಗನಿರ್ಣಯ ಮಾಡುವುದಿಲ್ಲ, ಚಿಕಿತ್ಸೆ ನೀಡುವುದಿಲ್ಲ; ನಿಮ್ಮ ವೈದ್ಯರನ್ನು ಬದಲಾಯಿಸುವುದಿಲ್ಲ. ನಿಮ್ಮ ಆರೋಗ್ಯ ಮಾಹಿತಿ ನಿಮ್ಮ ಖಾತೆಯಲ್ಲೇ ಇರುತ್ತದೆ ಮತ್ತು ಸುರಕ್ಷತೆಗಾಗಿ ಊಟದ ಸಲಹೆಗಳನ್ನು ಫಿಲ್ಟರ್ ಮಾಡಲು ಬಳಸಲಾಗುತ್ತದೆ.',
      'consent_privacy': 'ಪ್ರೊಫೈಲ್‌ನಿಂದ ಯಾವಾಗ ಬೇಕಾದರೂ ಡೇಟಾವನ್ನು ರಫ್ತು ಮಾಡಬಹುದು ಅಥವಾ ಅಳಿಸಬಹುದು.',
      'consent_agree': 'ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ; ಒಪ್ಪುತ್ತೇನೆ',
      'my_data': 'ನನ್ನ ಡೇಟಾ',
      'export_data': 'ಡೇಟಾ ರಫ್ತು ಮಾಡಿ',
      'export_ready': 'ರಫ್ತು ಉಳಿಸಲಾಗಿದೆ',
      'delete_account': 'ಖಾತೆ ಅಳಿಸಿ',
      'delete_account_title': 'ಖಾತೆ ಅಳಿಸಬೇಕೆ?',
      'delete_account_msg': 'ಇದು ನಿಮ್ಮ ಖಾತೆ, ಆರೋಗ್ಯ ದಾಖಲೆಗಳು, ಊಟದ ಯೋಜನೆಗಳನ್ನು ಶಾಶ್ವತವಾಗಿ ತೆಗೆದುಹಾಕುತ್ತದೆ. ಇದನ್ನು ಹಿಂತಿರುಗಿಸಲಾಗುವುದಿಲ್ಲ.',
      'delete_confirm': 'ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ',
    },
    'te': {
      'profile_completion_title': 'ప్రొఫైల్ పూర్తి చేయండి',
      'profile_completion_hint': 'గర్భధారణకు ముందు BMI మరియు గర్భ వారం సర్వర్‌లో లెక్కించబడతాయి.',
      'server_calculated_note': 'సర్వర్‌లో మీ కోసం లెక్కించబడింది (సమాచారం మాత్రమే)',
      'pre_pregnancy_bmi': 'గర్భధారణకు ముందు BMI',
      'pregnancy_week': 'వారం',
      'height_cm_label': 'ఎత్తు (సెం.మీ)',
      'height_cm_hint': 'ఉదా. 160',
      'prepreg_weight_label': 'గర్భధారణకు ముందు బరువు (కెజి)',
      'prepreg_weight_hint': 'గర్భధారణకు ముందు మీ బరువు',
      'lmp_date_label': 'చివరి ఋతుక్రమం మొదటి రోజు',
      'lmp_date_hint': 'తేదీ ఎంచుకోవడానికి నొక్కండి',
      'allergies_label': 'అలర్జీలు — ఇవి ఉన్న భోజనాలు ఎప్పుడూ మినహాయించబడతాయి',
      'cooking_time_label': 'వంట సమయ ప్రాధాన్యత',
      'budget_label': 'బడ్జెట్ ప్రాధాన్యత',
      'dislikes_label': 'ఇష్టపెట్టని పదార్థాలు',
      'dislikes_hint': 'ఉదా. పుట్టగొడ్డి',
      'save_and_continue': 'సేవ్ చేసి కొనసాగించండి',
      'profile_saved_incomplete': 'సేవ్ చేయబడింది — కొన్ని అవసరమైన వివరాలు ఇంకా మిగిలిపోయాయి.',
      'err_enter_height_weight': 'ఎత్తు మరియు గర్భధారణకు ముందు బరువును నమోదు చేయండి.',
      'profile_incomplete_title': 'కొన్ని వివరాలు కావాలి',
      'profile_incomplete_msg': 'వ్యక్తిగత భోజన సూచనల కోసం ఎత్తు, గర్భధారణకు ముందు బరువు, గర్భ తేదీ అవసరం.',
      'complete_profile': 'ప్రొఫైల్ పూర్తి చేయండి',
      'clinician_review_title': 'వైద్యుడి మార్గదర్శకత్వం సిఫార్సు',
      'clinician_review_msg': 'వ్యక్తిగత భోజన సూచనలకు ముందు వైద్యుడి ప్రత్యక్ష మార్గదర్శకత్వం అవసరం.',
      'no_safe_suggestion_title': 'ఇప్పుడు సురక్షితమైన సూచనలు లేవు',
      'no_safe_suggestion_msg': 'మీ భద్రతా ప్రొఫైల్‌కు సరిపోయే భోజనాలు లేవు. వైద్యుడిని సంప్రదించండి.',
      'consent_required_diet_msg': 'వ్యక్తిగత సూచనలకు ముందు సమ్మతి స్క్రీన్ చూడండి.',
      'review_consent': 'సమ్మతి చూడండి',
      'suggested_based_on': 'మీ ప్రాధాన్యతలు మరియు సమీక్షించిన భోజన కంటెంట్ ఆధారంగా.',
      'filtered_using': 'మీ అలర్జీ మరియు ఆహార సెట్టింగ్‌లను ఉపయోగించి ఫిల్టర్ చేయబడింది.',

      'app_name': 'అల్మాడైట్',
      'welcome': 'అల్మాడైట్‌కి స్వాగతం',
      'subtitle': 'మీ భాషలో గర్భధారణ పోషకాహార మద్దతు',
      'login': 'లాగిన్',
      'sign_in': 'సైన్ ఇన్',
      'register': 'నమోదు',
      'create_account': 'ఖాతా సృష్టించు',
      'email': 'ఇమెయిల్',
      'password': 'పాస్‌వర్డ్',
      'name': 'పూర్తి పేరు',
      'phone': 'ఫోన్ నంబర్',
      'home': 'హోమ్',
      'diet_plan': 'డైట్ ప్లాన్',
      'diet': 'ఆహారం',
      'urgent_help': 'అత్యవసర సహాయం',
      'emergency_help': 'అత్యవసర\nసహాయం',
      'profile': 'ప్రొఫైల్',
      'health_input': 'ఆరోగ్య డేటా',
      'generate_plan': 'భోజన సూచనలు పొందండి',
      'trimester': 'మూడు నెలల కాలం',
      'week': 'వారం',
      'breakfast': 'అల్పాహారం',
      'lunch': 'భోజనం',
      'dinner': 'రాత్రి భోజనం',
      'snacks': 'చిరుతిండి',
      'calories': 'కేలరీలు',
      'protein': 'ప్రోటీన్',
      'iron': 'ఐరన్',
      'calcium': 'కాల్షియం',
      'settings': 'సెట్టింగ్‌లు',
      'language': 'భాష',
      'logout': 'లాగ్‌అవుట్',
      'weight': 'బరువు (కి.గ్రా)',
      'hemoglobin': 'హిమోగ్లోబిన్ (గ్రా/డె.లి)',
      'blood_sugar': 'రక్తంలో చక్కెర (మి.గ్రా/డె.లి)',
      'blood_pressure': 'రక్తపోటు',
      'submit': 'సమర్పించు',
      'get_started': 'ప్రారంభించండి',
      'next': 'తరువాత',
      'skip': 'దాటవేయి',
      'welcome_back': 'మళ్ళీ స్వాగతం',
      'sign_in_continue': 'కొనసాగించడానికి సైన్ ఇన్ చేయండి',
      'no_account': 'ఖాతా లేదా? ',
      'has_account': 'ఇప్పటికే ఖాతా ఉందా? ',
      'start_journey': 'మీ గర్భధారణ పోషకాహారాన్ని నిర్వహించండి',
      'hello': 'నమస్కారం',
      'companion': 'మీ గర్భధారణ పోషకాహార సహచరుడు',
      'daily_tip': 'రోజువారీ సూచన',
      'health_input_label': 'ఆరోగ్య\nఇన్‌పుట్',
      'my_diet_plan': 'నా భోజన\nసూచనలు',
      'latest_health': 'ఇటీవలి ఆరోగ్య డేటా',
      'todays_meals': 'నేటి భోజన సూచనలు',
      'no_plan_yet': 'ఇంకా భోజన సూచనలు లేవు',
      'no_plan_desc': 'మీ ప్రాధాన్యతలకు అనుగుణంగా భోజన సూచనల కోసం మీ ఆరోగ్య డేటాను సమర్పించండి',
      'start_now': 'ఇప్పుడే ప్రారంభించండి',
      'loading_dashboard': 'డాష్‌బోర్డ్ లోడ్ అవుతోంది...',
      'loading_meal_plan': 'భోజన సూచనలు లోడ్ అవుతున్నాయి...',
      'no_diet_plan': 'ఆహార ప్రణాళిక లేదు',
      'no_diet_desc': 'ఈ వారం భోజన సూచనల కోసం మొదట మీ ఆరోగ్య డేటాను సమర్పించండి',
      'add_health_data': 'ఆరోగ్య డేటా జోడించండి',
      'daily_targets': 'రిఫరెన్స్ విలువలు',
      'dietary_alerts': 'భద్రతా గమనికలు',
      'pregnancy_info': 'గర్భధారణ సమాచారం',
      'health_vitals': 'ఆరోగ్య సూచికలు',
      'dietary_pref': 'ఆహారపు ప్రాధాన్యత',
      'bp_systolic': 'బీపీ సిస్టొలిక్',
      'bp_diastolic': 'బీపీ డయాస్టొలిక్',
      'fasting_sugar': 'ఉపవాస రక్తచక్కెర',
      'auto_generate': 'సేవ్ చేసిన తర్వాత భోజన సూచనలు',
      'generate_after': 'డేటా సేవ్ అయిన తర్వాత ఒక వారం భోజన సూచనలు',
      'submit_generate': 'సేవ్ & సూచనలు',
      'health_tip': 'సురక్షితమైన భోజన సూచనలను నిర్వహించడానికి మీ సమాచారం సహాయపడుతుంది. ఇది రోగనిర్ధారణకు ఉపయోగించబడదు.',
      'health_submitted': 'ఆరోగ్య డేటా సేవ్ చేయబడింది! భోజన సూచనలు సిద్ధం.',
      'health_failed': 'మీ డేటాను సేవ్ చేయడం సాధ్యం కాలేదు',
      'fix_errors_first': 'గుర్తించిన ఫీల్డ్‌లను ముందుగా సరిచేయండి.',
      'err_must_be_number': 'సంఖ్య అయి ఉండాలి',
      'err_must_be_between': '{min} మరియు {max} మధ్య ఉండాలి',
      'vital_hint_weight': 'సాధారణ పరిధి: 30–200 కి.గ్రా',
      'vital_hint_hemoglobin': 'సాధారణ పరిధి: 3–20 గ్రాం/డె.లి',
      'vital_hint_bp_sys': 'సాధారణ పరిధి: 60–250 mmHg',
      'vital_hint_bp_dia': 'సాధారణ పరిధి: 40–150 mmHg',
      'vital_hint_sugar': 'సాధారణ పరిధి: 20–600 మి.గ్రా/డె.లి',
      'region': 'ప్రాంతం',
      'age': 'వయస్సు',
      'height': 'ఎత్తు',
      'pre_weight': 'గర్భధారణకు ముందు బరువు',
      'edit_profile': 'ప్రొఫైల్ సవరించండి',
      'save_changes': 'మార్పులు సేవ్ చేయి',
      'profile_updated': 'ప్రొఫైల్ నవీకరించబడింది!',
      'profile_photo': 'ప్రొఫైల్ ఫోటో',
      'camera': 'కెమెరా',
      'gallery': 'గ్యాలరీ',
      'remove': 'తొలగించు',
      'exit_title': 'అల్మాడైట్ వదిలివేయాలా?',
      'exit_msg': 'మీ గురించి మీరే జాగ్రత్త వహించండి!\nనిష్క్రమించాలా?',
      'stay': 'ఉండు',
      'exit': 'నిష్క్రమించు',
      'page_not_found': 'పేజీ కనుగొనబడలేదు',
      'go_home': 'హోమ్‌కు వెళ్ళు',
      'non_veg': 'మాంసాహారం',
      'veg': 'శాకాహారం',
      'eggetarian': 'గుడ్డు ఆహారం',
      'first': 'మొదటి',
      'second': 'రెండవ',
      'third': 'మూడవ',
      'onboard_1_title': 'ఇద్దరికోసం బాగా తినండి',
      'onboard_1_desc': 'గర్భధారణ ప్రతి దశకు దక్షిణ భారత భోజన సూచనలను నిర్వహించండి.',
      'onboard_2_title': 'స్పష్టమైన, సురక్షితమైన సూచనలు',
      'onboard_2_desc': 'భోజన సూచనలు మీ అలర్జీలు, ప్రాధాన్యతలు, గర్భధారణ దశను గౌరవిస్తాయి — ప్రతి సూచనకు కారణం చూపబడుతుంది.',
      'onboard_3_title': 'ప్రాంతీయ & బహుభాష',
      'onboard_3_desc': 'కేరళ, తమిళనాడు, కర్ణాటక, ఆంధ్ర — మీ భాషలో మరియు మీ ప్రాంతపు భోజనం.',
      'analyzing': 'ఆరోగ్య డేటా సేవ్ చేయబడుతోంది\nభోజన సూచనలు సిద్ధమవుతున్నాయి...',
      'loading': 'లోడ్ అవుతోంది...',
      'error_generic': 'ఏదో తప్పు జరిగింది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
      'retry': 'మళ్ళీ ప్రయత్నించండి',
      'urgent_note_title': 'వైద్యుడికి గమనిక',
      'urgent_note_hint': 'మీకు ఏమి అనిపిస్తోంది, ఎప్పుడు ప్రారంభమైంది, ఎన్నిసార్లు అని వివరించండి...',
      'save_note': 'గమనిక సేవ్ చేయండి',
      'note_saved': 'గమనిక సేవ్ చేయబడింది. వైద్యుడితో పంచుకోండి.',
      'add_note': 'గమనిక జోడించండి',
      'urgent_app_cannot': 'ఈ యాప్ అత్యవసర పరిస్థితులను అంచనా వేయలేదు',
      'urgent_disclaimer_fallback': 'అల్మాడైట్ అత్యవసర పరిస్థితులను లేదా తక్షణ లక్షణాలను అంచనా వేయలేదు. ఈ స్క్రీన్ భద్రతా సమాచారాన్ని మాత్రమే అందిస్తుంది; ఇది వైద్య సలహా కాదు.',
      'urgent_warning_signs': 'హెచ్చరిక సంకేతాలు — వైద్య సహాయం పొందండి',
      'urgent_contacts': 'ఎవరిని సంప్రదించాలి',
      'emergency_number': 'అత్యవసరం',
      'ambulance_number': 'అంబులెన్స్',
      'urgent_clinician_checklist': 'వైద్యుడిని పిలవడానికి ముందు',
      'your_notes': 'మీ గమనికలు',
      'vitals_optional': 'అన్ని ఫీల్డ్‌లు ఐచ్ఛికం — తెలియనివి వదిలివేయండి. ఏదీ ఊహించబడదు.',
      'allergies': 'అలర్జీలు',
      'allergies_hint': 'ఇక్కడ జాబితా చేసిన ఆహారాలు అన్ని భోజన సూచనల నుండి పూర్తిగా మినహాయించబడతాయి.',
      'allergy_placeholder': 'ఉదా. వేరుశనగ, గుడ్డు, రొయ్య...',
      'add_allergy': 'అలర్జీ జోడించు',
      'swap_meal': 'భోజనం మార్చు',
      'swap_done': 'భోజనం మార్చబడింది — భద్రతా ఫిల్టర్‌లు మళ్ళీ వర్తింపజేయబడ్డాయి.',
      'why_suggested': 'సూచించిన కారణం',
      'reference_only': 'రిఫరెన్స్ విలువలు మాత్రమే — సూచన కాదు. లక్ష్యాల గురించి వైద్యుడితో చర్చించండి.',
      'day': 'రోజు',
      'today_badge': 'ఈరోజు',
      'allergens_section': 'అలర్జీ వర్గాలు',
      'no_known_allergens': 'ఈ భోజనానికి నమోదైన అలర్జీ వర్గాలు లేవు.',
      'nutrition_per_serving': 'ఒక సర్వింగ్‌లో పోషకాలు',
      'carbs': 'పిండి పదార్థాలు',
      'fat': 'కొవ్వు',
      'folate': 'ఫోలేట్',
      'fiber': 'ఫైబర్',
      'ingredients': 'పదార్థాలు',
      'food_safety': 'ఆహార భద్రతా గమనికలు',
      'cautions': 'జాగ్రత్తలు',
      'about_this_info': 'ఈ సమాచారం గురించి',
      'source': 'మూలం',
      'not_documented': 'నమోదు కాలేదు',
      'content_version': 'కంటెంట్ సంస్కరణ',
      'review_status': 'సమీక్ష స్థితి',
      'consent_title': 'ప్రారంభించే ముందు',
      'consent_body': 'అల్మాడైట్ పోషకాహార సమాచారం మరియు భోజన సూచనలను నిర్వహిస్తుంది. ఇది రోగనిర్ధారణ చేయదు, చికిత్స చేయదు; మీ వైద్యుడిని భర్తీ చేయదు. మీ ఆరోగ్య సమాచారం మీ ఖాతాలోనే ఉంటుంది, భద్రత కోసం భోజన సూచనలను ఫిల్టర్ చేయడానికి ఉపయోగించబడుతుంది.',
      'consent_privacy': 'మీ ప్రొఫైల్ నుండి ఎప్పుడైనా డేటాను ఎగుమతి చేయవచ్చు లేదా తొలగించవచ్చు.',
      'consent_agree': 'అర్థం చేసుకున్నాను; అంగీకరిస్తున్నాను',
      'my_data': 'నా డేటా',
      'export_data': 'డేటా ఎగుమతి చేయండి',
      'export_ready': 'ఎగుమతి సేవ్ చేయబడింది',
      'delete_account': 'ఖాతా తొలగించు',
      'delete_account_title': 'ఖాతా తొలగించాలా?',
      'delete_account_msg': 'ఇది మీ ఖాతా, ఆరోగ్య రికార్డులు, భోజన ప్రణాళికలను శాశ్వతంగా తొలగిస్తుంది. ఇది రద్దు చేయబడదు.',
      'delete_confirm': 'శాశ్వతంగా తొలగించు',
    },
  };

  String tr(String key) {
    return _localizedValues[locale.languageCode]?[key]
        ?? _localizedValues['en']![key]
        ?? key;
  }

  /// All keys defined for a language (used by the completeness test).
  static Set<String> keysFor(String languageCode) =>
      _localizedValues[languageCode]?.keys.toSet() ?? {};

  static Set<String> get englishKeys => _localizedValues['en']!.keys.toSet();

  /// Returns the localized meal name based on the current locale.
  /// Falls back to English name if the localized name is null or empty.
  String mealName(Map<String, dynamic> meal) {
    final lang = locale.languageCode;
    String? localized;
    switch (lang) {
      case 'ta':
        localized = meal['name_tamil'] as String?;
        break;
      case 'ml':
        localized = meal['name_malayalam'] as String?;
        break;
      case 'kn':
        localized = meal['name_kannada'] as String?;
        break;
      case 'te':
        localized = meal['name_telugu'] as String?;
        break;
    }
    if (localized != null && localized.isNotEmpty) return localized;
    return meal['name'] ?? 'Meal';
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ml', 'ta', 'kn', 'te'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
